<?php

	/**
	 * FontAwesome Icon List for version 5.0.8
	 * This is a format best suited for general use in PHP
	 * @author: Theo Komninos
	 * @version: 0.0.1
	 * @todo: Names might need a bit of polishing, since they've been autogenerated.
	 */

	const FONT_AWESOME = [
	[
		"name" => "500px", 
		"icon" => "500px", 
		"code" => "f26e", 
	],
	[
		"name" => "Accessible Icon", 
		"icon" => "accessible-icon", 
		"code" => "f368", 
	],
	[
		"name" => "Accusoft", 
		"icon" => "accusoft", 
		"code" => "f369", 
	],
	[
		"name" => "Address Book", 
		"icon" => "address-book", 
		"code" => "f2b9", 
	],
	[
		"name" => "Address Card", 
		"icon" => "address-card", 
		"code" => "f2bb", 
	],
	[
		"name" => "Adjust", 
		"icon" => "adjust", 
		"code" => "f042", 
	],
	[
		"name" => "Adn", 
		"icon" => "adn", 
		"code" => "f170", 
	],
	[
		"name" => "Adversal", 
		"icon" => "adversal", 
		"code" => "f36a", 
	],
	[
		"name" => "Affiliatetheme", 
		"icon" => "affiliatetheme", 
		"code" => "f36b", 
	],
	[
		"name" => "Algolia", 
		"icon" => "algolia", 
		"code" => "f36c", 
	],
	[
		"name" => "Align Center", 
		"icon" => "align-center", 
		"code" => "f037", 
	],
	[
		"name" => "Align Justify", 
		"icon" => "align-justify", 
		"code" => "f039", 
	],
	[
		"name" => "Align Left", 
		"icon" => "align-left", 
		"code" => "f036", 
	],
	[
		"name" => "Align Right", 
		"icon" => "align-right", 
		"code" => "f038", 
	],
	[
		"name" => "Amazon", 
		"icon" => "amazon", 
		"code" => "f270", 
	],
	[
		"name" => "Amazon Pay", 
		"icon" => "amazon-pay", 
		"code" => "f42c", 
	],
	[
		"name" => "Ambulance", 
		"icon" => "ambulance", 
		"code" => "f0f9", 
	],
	[
		"name" => "American Sign Language Interpreting", 
		"icon" => "american-sign-language-interpreting", 
		"code" => "f2a3", 
	],
	[
		"name" => "Amilia", 
		"icon" => "amilia", 
		"code" => "f36d", 
	],
	[
		"name" => "Anchor", 
		"icon" => "anchor", 
		"code" => "f13d", 
	],
	[
		"name" => "Android", 
		"icon" => "android", 
		"code" => "f17b", 
	],
	[
		"name" => "Angellist", 
		"icon" => "angellist", 
		"code" => "f209", 
	],
	[
		"name" => "Angle Double Down", 
		"icon" => "angle-double-down", 
		"code" => "f103", 
	],
	[
		"name" => "Angle Double Left", 
		"icon" => "angle-double-left", 
		"code" => "f100", 
	],
	[
		"name" => "Angle Double Right", 
		"icon" => "angle-double-right", 
		"code" => "f101", 
	],
	[
		"name" => "Angle Double Up", 
		"icon" => "angle-double-up", 
		"code" => "f102", 
	],
	[
		"name" => "Angle Down", 
		"icon" => "angle-down", 
		"code" => "f107", 
	],
	[
		"name" => "Angle Left", 
		"icon" => "angle-left", 
		"code" => "f104", 
	],
	[
		"name" => "Angle Right", 
		"icon" => "angle-right", 
		"code" => "f105", 
	],
	[
		"name" => "Angle Up", 
		"icon" => "angle-up", 
		"code" => "f106", 
	],
	[
		"name" => "Angrycreative", 
		"icon" => "angrycreative", 
		"code" => "f36e", 
	],
	[
		"name" => "Angular", 
		"icon" => "angular", 
		"code" => "f420", 
	],
	[
		"name" => "App Store", 
		"icon" => "app-store", 
		"code" => "f36f", 
	],
	[
		"name" => "App Store Ios", 
		"icon" => "app-store-ios", 
		"code" => "f370", 
	],
	[
		"name" => "Apper", 
		"icon" => "apper", 
		"code" => "f371", 
	],
	[
		"name" => "Apple", 
		"icon" => "apple", 
		"code" => "f179", 
	],
	[
		"name" => "Apple Pay", 
		"icon" => "apple-pay", 
		"code" => "f415", 
	],
	[
		"name" => "Archive", 
		"icon" => "archive", 
		"code" => "f187", 
	],
	[
		"name" => "Arrow Alt Circle Down", 
		"icon" => "arrow-alt-circle-down", 
		"code" => "f358", 
	],
	[
		"name" => "Arrow Alt Circle Left", 
		"icon" => "arrow-alt-circle-left", 
		"code" => "f359", 
	],
	[
		"name" => "Arrow Alt Circle Right", 
		"icon" => "arrow-alt-circle-right", 
		"code" => "f35a", 
	],
	[
		"name" => "Arrow Alt Circle Up", 
		"icon" => "arrow-alt-circle-up", 
		"code" => "f35b", 
	],
	[
		"name" => "Arrow Circle Down", 
		"icon" => "arrow-circle-down", 
		"code" => "f0ab", 
	],
	[
		"name" => "Arrow Circle Left", 
		"icon" => "arrow-circle-left", 
		"code" => "f0a8", 
	],
	[
		"name" => "Arrow Circle Right", 
		"icon" => "arrow-circle-right", 
		"code" => "f0a9", 
	],
	[
		"name" => "Arrow Circle Up", 
		"icon" => "arrow-circle-up", 
		"code" => "f0aa", 
	],
	[
		"name" => "Arrow Down", 
		"icon" => "arrow-down", 
		"code" => "f063", 
	],
	[
		"name" => "Arrow Left", 
		"icon" => "arrow-left", 
		"code" => "f060", 
	],
	[
		"name" => "Arrow Right", 
		"icon" => "arrow-right", 
		"code" => "f061", 
	],
	[
		"name" => "Arrow Up", 
		"icon" => "arrow-up", 
		"code" => "f062", 
	],
	[
		"name" => "Arrows Alt", 
		"icon" => "arrows-alt", 
		"code" => "f0b2", 
	],
	[
		"name" => "Arrows Alt H", 
		"icon" => "arrows-alt-h", 
		"code" => "f337", 
	],
	[
		"name" => "Arrows Alt V", 
		"icon" => "arrows-alt-v", 
		"code" => "f338", 
	],
	[
		"name" => "Assistive Listening Systems", 
		"icon" => "assistive-listening-systems", 
		"code" => "f2a2", 
	],
	[
		"name" => "Asterisk", 
		"icon" => "asterisk", 
		"code" => "f069", 
	],
	[
		"name" => "Asymmetrik", 
		"icon" => "asymmetrik", 
		"code" => "f372", 
	],
	[
		"name" => "At", 
		"icon" => "at", 
		"code" => "f1fa", 
	],
	[
		"name" => "Audible", 
		"icon" => "audible", 
		"code" => "f373", 
	],
	[
		"name" => "Audio Description", 
		"icon" => "audio-description", 
		"code" => "f29e", 
	],
	[
		"name" => "Autoprefixer", 
		"icon" => "autoprefixer", 
		"code" => "f41c", 
	],
	[
		"name" => "Avianex", 
		"icon" => "avianex", 
		"code" => "f374", 
	],
	[
		"name" => "Aviato", 
		"icon" => "aviato", 
		"code" => "f421", 
	],
	[
		"name" => "Aws", 
		"icon" => "aws", 
		"code" => "f375", 
	],
	[
		"name" => "Backward", 
		"icon" => "backward", 
		"code" => "f04a", 
	],
	[
		"name" => "Balance Scale", 
		"icon" => "balance-scale", 
		"code" => "f24e", 
	],
	[
		"name" => "Ban", 
		"icon" => "ban", 
		"code" => "f05e", 
	],
	[
		"name" => "Band Aid", 
		"icon" => "band-aid", 
		"code" => "f462", 
	],
	[
		"name" => "Bandcamp", 
		"icon" => "bandcamp", 
		"code" => "f2d5", 
	],
	[
		"name" => "Barcode", 
		"icon" => "barcode", 
		"code" => "f02a", 
	],
	[
		"name" => "Bars", 
		"icon" => "bars", 
		"code" => "f0c9", 
	],
	[
		"name" => "Baseball Ball", 
		"icon" => "baseball-ball", 
		"code" => "f433", 
	],
	[
		"name" => "Basketball Ball", 
		"icon" => "basketball-ball", 
		"code" => "f434", 
	],
	[
		"name" => "Bath", 
		"icon" => "bath", 
		"code" => "f2cd", 
	],
	[
		"name" => "Battery Empty", 
		"icon" => "battery-empty", 
		"code" => "f244", 
	],
	[
		"name" => "Battery Full", 
		"icon" => "battery-full", 
		"code" => "f240", 
	],
	[
		"name" => "Battery Half", 
		"icon" => "battery-half", 
		"code" => "f242", 
	],
	[
		"name" => "Battery Quarter", 
		"icon" => "battery-quarter", 
		"code" => "f243", 
	],
	[
		"name" => "Battery Three Quarters", 
		"icon" => "battery-three-quarters", 
		"code" => "f241", 
	],
	[
		"name" => "Bed", 
		"icon" => "bed", 
		"code" => "f236", 
	],
	[
		"name" => "Beer", 
		"icon" => "beer", 
		"code" => "f0fc", 
	],
	[
		"name" => "Behance", 
		"icon" => "behance", 
		"code" => "f1b4", 
	],
	[
		"name" => "Behance Square", 
		"icon" => "behance-square", 
		"code" => "f1b5", 
	],
	[
		"name" => "Bell", 
		"icon" => "bell", 
		"code" => "f0f3", 
	],
	[
		"name" => "Bell Slash", 
		"icon" => "bell-slash", 
		"code" => "f1f6", 
	],
	[
		"name" => "Bicycle", 
		"icon" => "bicycle", 
		"code" => "f206", 
	],
	[
		"name" => "Bimobject", 
		"icon" => "bimobject", 
		"code" => "f378", 
	],
	[
		"name" => "Binoculars", 
		"icon" => "binoculars", 
		"code" => "f1e5", 
	],
	[
		"name" => "Birthday Cake", 
		"icon" => "birthday-cake", 
		"code" => "f1fd", 
	],
	[
		"name" => "Bitbucket", 
		"icon" => "bitbucket", 
		"code" => "f171", 
	],
	[
		"name" => "Bitcoin", 
		"icon" => "bitcoin", 
		"code" => "f379", 
	],
	[
		"name" => "Bity", 
		"icon" => "bity", 
		"code" => "f37a", 
	],
	[
		"name" => "Black Tie", 
		"icon" => "black-tie", 
		"code" => "f27e", 
	],
	[
		"name" => "Blackberry", 
		"icon" => "blackberry", 
		"code" => "f37b", 
	],
	[
		"name" => "Blind", 
		"icon" => "blind", 
		"code" => "f29d", 
	],
	[
		"name" => "Blogger", 
		"icon" => "blogger", 
		"code" => "f37c", 
	],
	[
		"name" => "Blogger B", 
		"icon" => "blogger-b", 
		"code" => "f37d", 
	],
	[
		"name" => "Bluetooth", 
		"icon" => "bluetooth", 
		"code" => "f293", 
	],
	[
		"name" => "Bluetooth B", 
		"icon" => "bluetooth-b", 
		"code" => "f294", 
	],
	[
		"name" => "Bold", 
		"icon" => "bold", 
		"code" => "f032", 
	],
	[
		"name" => "Bolt", 
		"icon" => "bolt", 
		"code" => "f0e7", 
	],
	[
		"name" => "Bomb", 
		"icon" => "bomb", 
		"code" => "f1e2", 
	],
	[
		"name" => "Book", 
		"icon" => "book", 
		"code" => "f02d", 
	],
	[
		"name" => "Bookmark", 
		"icon" => "bookmark", 
		"code" => "f02e", 
	],
	[
		"name" => "Bowling Ball", 
		"icon" => "bowling-ball", 
		"code" => "f436", 
	],
	[
		"name" => "Box", 
		"icon" => "box", 
		"code" => "f466", 
	],
	[
		"name" => "Boxes", 
		"icon" => "boxes", 
		"code" => "f468", 
	],
	[
		"name" => "Braille", 
		"icon" => "braille", 
		"code" => "f2a1", 
	],
	[
		"name" => "Briefcase", 
		"icon" => "briefcase", 
		"code" => "f0b1", 
	],
	[
		"name" => "Btc", 
		"icon" => "btc", 
		"code" => "f15a", 
	],
	[
		"name" => "Bug", 
		"icon" => "bug", 
		"code" => "f188", 
	],
	[
		"name" => "Building", 
		"icon" => "building", 
		"code" => "f1ad", 
	],
	[
		"name" => "Bullhorn", 
		"icon" => "bullhorn", 
		"code" => "f0a1", 
	],
	[
		"name" => "Bullseye", 
		"icon" => "bullseye", 
		"code" => "f140", 
	],
	[
		"name" => "Buromobelexperte", 
		"icon" => "buromobelexperte", 
		"code" => "f37f", 
	],
	[
		"name" => "Bus", 
		"icon" => "bus", 
		"code" => "f207", 
	],
	[
		"name" => "Buysellads", 
		"icon" => "buysellads", 
		"code" => "f20d", 
	],
	[
		"name" => "Calculator", 
		"icon" => "calculator", 
		"code" => "f1ec", 
	],
	[
		"name" => "Calendar", 
		"icon" => "calendar", 
		"code" => "f133", 
	],
	[
		"name" => "Calendar Alt", 
		"icon" => "calendar-alt", 
		"code" => "f073", 
	],
	[
		"name" => "Calendar Check", 
		"icon" => "calendar-check", 
		"code" => "f274", 
	],
	[
		"name" => "Calendar Minus", 
		"icon" => "calendar-minus", 
		"code" => "f272", 
	],
	[
		"name" => "Calendar Plus", 
		"icon" => "calendar-plus", 
		"code" => "f271", 
	],
	[
		"name" => "Calendar Times", 
		"icon" => "calendar-times", 
		"code" => "f273", 
	],
	[
		"name" => "Camera", 
		"icon" => "camera", 
		"code" => "f030", 
	],
	[
		"name" => "Camera Retro", 
		"icon" => "camera-retro", 
		"code" => "f083", 
	],
	[
		"name" => "Car", 
		"icon" => "car", 
		"code" => "f1b9", 
	],
	[
		"name" => "Caret Down", 
		"icon" => "caret-down", 
		"code" => "f0d7", 
	],
	[
		"name" => "Caret Left", 
		"icon" => "caret-left", 
		"code" => "f0d9", 
	],
	[
		"name" => "Caret Right", 
		"icon" => "caret-right", 
		"code" => "f0da", 
	],
	[
		"name" => "Caret Square Down", 
		"icon" => "caret-square-down", 
		"code" => "f150", 
	],
	[
		"name" => "Caret Square Left", 
		"icon" => "caret-square-left", 
		"code" => "f191", 
	],
	[
		"name" => "Caret Square Right", 
		"icon" => "caret-square-right", 
		"code" => "f152", 
	],
	[
		"name" => "Caret Square Up", 
		"icon" => "caret-square-up", 
		"code" => "f151", 
	],
	[
		"name" => "Caret Up", 
		"icon" => "caret-up", 
		"code" => "f0d8", 
	],
	[
		"name" => "Cart Arrow Down", 
		"icon" => "cart-arrow-down", 
		"code" => "f218", 
	],
	[
		"name" => "Cart Plus", 
		"icon" => "cart-plus", 
		"code" => "f217", 
	],
	[
		"name" => "Cc Amazon Pay", 
		"icon" => "cc-amazon-pay", 
		"code" => "f42d", 
	],
	[
		"name" => "Cc Amex", 
		"icon" => "cc-amex", 
		"code" => "f1f3", 
	],
	[
		"name" => "Cc Apple Pay", 
		"icon" => "cc-apple-pay", 
		"code" => "f416", 
	],
	[
		"name" => "Cc Diners Club", 
		"icon" => "cc-diners-club", 
		"code" => "f24c", 
	],
	[
		"name" => "Cc Discover", 
		"icon" => "cc-discover", 
		"code" => "f1f2", 
	],
	[
		"name" => "Cc Jcb", 
		"icon" => "cc-jcb", 
		"code" => "f24b", 
	],
	[
		"name" => "Cc Mastercard", 
		"icon" => "cc-mastercard", 
		"code" => "f1f1", 
	],
	[
		"name" => "Cc Paypal", 
		"icon" => "cc-paypal", 
		"code" => "f1f4", 
	],
	[
		"name" => "Cc Stripe", 
		"icon" => "cc-stripe", 
		"code" => "f1f5", 
	],
	[
		"name" => "Cc Visa", 
		"icon" => "cc-visa", 
		"code" => "f1f0", 
	],
	[
		"name" => "Centercode", 
		"icon" => "centercode", 
		"code" => "f380", 
	],
	[
		"name" => "Certificate", 
		"icon" => "certificate", 
		"code" => "f0a3", 
	],
	[
		"name" => "Chart Area", 
		"icon" => "chart-area", 
		"code" => "f1fe", 
	],
	[
		"name" => "Chart Bar", 
		"icon" => "chart-bar", 
		"code" => "f080", 
	],
	[
		"name" => "Chart Line", 
		"icon" => "chart-line", 
		"code" => "f201", 
	],
	[
		"name" => "Chart Pie", 
		"icon" => "chart-pie", 
		"code" => "f200", 
	],
	[
		"name" => "Check", 
		"icon" => "check", 
		"code" => "f00c", 
	],
	[
		"name" => "Check Circle", 
		"icon" => "check-circle", 
		"code" => "f058", 
	],
	[
		"name" => "Check Square", 
		"icon" => "check-square", 
		"code" => "f14a", 
	],
	[
		"name" => "Chess", 
		"icon" => "chess", 
		"code" => "f439", 
	],
	[
		"name" => "Chess Bishop", 
		"icon" => "chess-bishop", 
		"code" => "f43a", 
	],
	[
		"name" => "Chess Board", 
		"icon" => "chess-board", 
		"code" => "f43c", 
	],
	[
		"name" => "Chess King", 
		"icon" => "chess-king", 
		"code" => "f43f", 
	],
	[
		"name" => "Chess Knight", 
		"icon" => "chess-knight", 
		"code" => "f441", 
	],
	[
		"name" => "Chess Pawn", 
		"icon" => "chess-pawn", 
		"code" => "f443", 
	],
	[
		"name" => "Chess Queen", 
		"icon" => "chess-queen", 
		"code" => "f445", 
	],
	[
		"name" => "Chess Rook", 
		"icon" => "chess-rook", 
		"code" => "f447", 
	],
	[
		"name" => "Chevron Circle Down", 
		"icon" => "chevron-circle-down", 
		"code" => "f13a", 
	],
	[
		"name" => "Chevron Circle Left", 
		"icon" => "chevron-circle-left", 
		"code" => "f137", 
	],
	[
		"name" => "Chevron Circle Right", 
		"icon" => "chevron-circle-right", 
		"code" => "f138", 
	],
	[
		"name" => "Chevron Circle Up", 
		"icon" => "chevron-circle-up", 
		"code" => "f139", 
	],
	[
		"name" => "Chevron Down", 
		"icon" => "chevron-down", 
		"code" => "f078", 
	],
	[
		"name" => "Chevron Left", 
		"icon" => "chevron-left", 
		"code" => "f053", 
	],
	[
		"name" => "Chevron Right", 
		"icon" => "chevron-right", 
		"code" => "f054", 
	],
	[
		"name" => "Chevron Up", 
		"icon" => "chevron-up", 
		"code" => "f077", 
	],
	[
		"name" => "Child", 
		"icon" => "child", 
		"code" => "f1ae", 
	],
	[
		"name" => "Chrome", 
		"icon" => "chrome", 
		"code" => "f268", 
	],
	[
		"name" => "Circle", 
		"icon" => "circle", 
		"code" => "f111", 
	],
	[
		"name" => "Circle Notch", 
		"icon" => "circle-notch", 
		"code" => "f1ce", 
	],
	[
		"name" => "Clipboard", 
		"icon" => "clipboard", 
		"code" => "f328", 
	],
	[
		"name" => "Clipboard Check", 
		"icon" => "clipboard-check", 
		"code" => "f46c", 
	],
	[
		"name" => "Clipboard List", 
		"icon" => "clipboard-list", 
		"code" => "f46d", 
	],
	[
		"name" => "Clock", 
		"icon" => "clock", 
		"code" => "f017", 
	],
	[
		"name" => "Clone", 
		"icon" => "clone", 
		"code" => "f24d", 
	],
	[
		"name" => "Closed Captioning", 
		"icon" => "closed-captioning", 
		"code" => "f20a", 
	],
	[
		"name" => "Cloud", 
		"icon" => "cloud", 
		"code" => "f0c2", 
	],
	[
		"name" => "Cloud Download Alt", 
		"icon" => "cloud-download-alt", 
		"code" => "f381", 
	],
	[
		"name" => "Cloud Upload Alt", 
		"icon" => "cloud-upload-alt", 
		"code" => "f382", 
	],
	[
		"name" => "Cloudscale", 
		"icon" => "cloudscale", 
		"code" => "f383", 
	],
	[
		"name" => "Cloudsmith", 
		"icon" => "cloudsmith", 
		"code" => "f384", 
	],
	[
		"name" => "Cloudversify", 
		"icon" => "cloudversify", 
		"code" => "f385", 
	],
	[
		"name" => "Code", 
		"icon" => "code", 
		"code" => "f121", 
	],
	[
		"name" => "Code Branch", 
		"icon" => "code-branch", 
		"code" => "f126", 
	],
	[
		"name" => "Codepen", 
		"icon" => "codepen", 
		"code" => "f1cb", 
	],
	[
		"name" => "Codiepie", 
		"icon" => "codiepie", 
		"code" => "f284", 
	],
	[
		"name" => "Coffee", 
		"icon" => "coffee", 
		"code" => "f0f4", 
	],
	[
		"name" => "Cog", 
		"icon" => "cog", 
		"code" => "f013", 
	],
	[
		"name" => "Cogs", 
		"icon" => "cogs", 
		"code" => "f085", 
	],
	[
		"name" => "Columns", 
		"icon" => "columns", 
		"code" => "f0db", 
	],
	[
		"name" => "Comment", 
		"icon" => "comment", 
		"code" => "f075", 
	],
	[
		"name" => "Comment Alt", 
		"icon" => "comment-alt", 
		"code" => "f27a", 
	],
	[
		"name" => "Comments", 
		"icon" => "comments", 
		"code" => "f086", 
	],
	[
		"name" => "Compass", 
		"icon" => "compass", 
		"code" => "f14e", 
	],
	[
		"name" => "Compress", 
		"icon" => "compress", 
		"code" => "f066", 
	],
	[
		"name" => "Connectdevelop", 
		"icon" => "connectdevelop", 
		"code" => "f20e", 
	],
	[
		"name" => "Contao", 
		"icon" => "contao", 
		"code" => "f26d", 
	],
	[
		"name" => "Copy", 
		"icon" => "copy", 
		"code" => "f0c5", 
	],
	[
		"name" => "Copyright", 
		"icon" => "copyright", 
		"code" => "f1f9", 
	],
	[
		"name" => "Cpanel", 
		"icon" => "cpanel", 
		"code" => "f388", 
	],
	[
		"name" => "Creative Commons", 
		"icon" => "creative-commons", 
		"code" => "f25e", 
	],
	[
		"name" => "Credit Card", 
		"icon" => "credit-card", 
		"code" => "f09d", 
	],
	[
		"name" => "Crop", 
		"icon" => "crop", 
		"code" => "f125", 
	],
	[
		"name" => "Crosshairs", 
		"icon" => "crosshairs", 
		"code" => "f05b", 
	],
	[
		"name" => "Css3", 
		"icon" => "css3", 
		"code" => "f13c", 
	],
	[
		"name" => "Css3 Alt", 
		"icon" => "css3-alt", 
		"code" => "f38b", 
	],
	[
		"name" => "Cube", 
		"icon" => "cube", 
		"code" => "f1b2", 
	],
	[
		"name" => "Cubes", 
		"icon" => "cubes", 
		"code" => "f1b3", 
	],
	[
		"name" => "Cut", 
		"icon" => "cut", 
		"code" => "f0c4", 
	],
	[
		"name" => "Cuttlefish", 
		"icon" => "cuttlefish", 
		"code" => "f38c", 
	],
	[
		"name" => "D And D", 
		"icon" => "d-and-d", 
		"code" => "f38d", 
	],
	[
		"name" => "Dashcube", 
		"icon" => "dashcube", 
		"code" => "f210", 
	],
	[
		"name" => "Database", 
		"icon" => "database", 
		"code" => "f1c0", 
	],
	[
		"name" => "Deaf", 
		"icon" => "deaf", 
		"code" => "f2a4", 
	],
	[
		"name" => "Delicious", 
		"icon" => "delicious", 
		"code" => "f1a5", 
	],
	[
		"name" => "Deploydog", 
		"icon" => "deploydog", 
		"code" => "f38e", 
	],
	[
		"name" => "Deskpro", 
		"icon" => "deskpro", 
		"code" => "f38f", 
	],
	[
		"name" => "Desktop", 
		"icon" => "desktop", 
		"code" => "f108", 
	],
	[
		"name" => "Deviantart", 
		"icon" => "deviantart", 
		"code" => "f1bd", 
	],
	[
		"name" => "Digg", 
		"icon" => "digg", 
		"code" => "f1a6", 
	],
	[
		"name" => "Digital Ocean", 
		"icon" => "digital-ocean", 
		"code" => "f391", 
	],
	[
		"name" => "Discord", 
		"icon" => "discord", 
		"code" => "f392", 
	],
	[
		"name" => "Discourse", 
		"icon" => "discourse", 
		"code" => "f393", 
	],
	[
		"name" => "Dna", 
		"icon" => "dna", 
		"code" => "f471", 
	],
	[
		"name" => "Dochub", 
		"icon" => "dochub", 
		"code" => "f394", 
	],
	[
		"name" => "Docker", 
		"icon" => "docker", 
		"code" => "f395", 
	],
	[
		"name" => "Dollar Sign", 
		"icon" => "dollar-sign", 
		"code" => "f155", 
	],
	[
		"name" => "Dolly", 
		"icon" => "dolly", 
		"code" => "f472", 
	],
	[
		"name" => "Dolly Flatbed", 
		"icon" => "dolly-flatbed", 
		"code" => "f474", 
	],
	[
		"name" => "Dot Circle", 
		"icon" => "dot-circle", 
		"code" => "f192", 
	],
	[
		"name" => "Download", 
		"icon" => "download", 
		"code" => "f019", 
	],
	[
		"name" => "Draft2digital", 
		"icon" => "draft2digital", 
		"code" => "f396", 
	],
	[
		"name" => "Dribbble", 
		"icon" => "dribbble", 
		"code" => "f17d", 
	],
	[
		"name" => "Dribbble Square", 
		"icon" => "dribbble-square", 
		"code" => "f397", 
	],
	[
		"name" => "Dropbox", 
		"icon" => "dropbox", 
		"code" => "f16b", 
	],
	[
		"name" => "Drupal", 
		"icon" => "drupal", 
		"code" => "f1a9", 
	],
	[
		"name" => "Dyalog", 
		"icon" => "dyalog", 
		"code" => "f399", 
	],
	[
		"name" => "Earlybirds", 
		"icon" => "earlybirds", 
		"code" => "f39a", 
	],
	[
		"name" => "Edge", 
		"icon" => "edge", 
		"code" => "f282", 
	],
	[
		"name" => "Edit", 
		"icon" => "edit", 
		"code" => "f044", 
	],
	[
		"name" => "Eject", 
		"icon" => "eject", 
		"code" => "f052", 
	],
	[
		"name" => "Elementor", 
		"icon" => "elementor", 
		"code" => "f430", 
	],
	[
		"name" => "Ellipsis H", 
		"icon" => "ellipsis-h", 
		"code" => "f141", 
	],
	[
		"name" => "Ellipsis V", 
		"icon" => "ellipsis-v", 
		"code" => "f142", 
	],
	[
		"name" => "Ember", 
		"icon" => "ember", 
		"code" => "f423", 
	],
	[
		"name" => "Empire", 
		"icon" => "empire", 
		"code" => "f1d1", 
	],
	[
		"name" => "Envelope", 
		"icon" => "envelope", 
		"code" => "f0e0", 
	],
	[
		"name" => "Envelope Open", 
		"icon" => "envelope-open", 
		"code" => "f2b6", 
	],
	[
		"name" => "Envelope Square", 
		"icon" => "envelope-square", 
		"code" => "f199", 
	],
	[
		"name" => "Envira", 
		"icon" => "envira", 
		"code" => "f299", 
	],
	[
		"name" => "Eraser", 
		"icon" => "eraser", 
		"code" => "f12d", 
	],
	[
		"name" => "Erlang", 
		"icon" => "erlang", 
		"code" => "f39d", 
	],
	[
		"name" => "Ethereum", 
		"icon" => "ethereum", 
		"code" => "f42e", 
	],
	[
		"name" => "Etsy", 
		"icon" => "etsy", 
		"code" => "f2d7", 
	],
	[
		"name" => "Euro Sign", 
		"icon" => "euro-sign", 
		"code" => "f153", 
	],
	[
		"name" => "Exchange Alt", 
		"icon" => "exchange-alt", 
		"code" => "f362", 
	],
	[
		"name" => "Exclamation", 
		"icon" => "exclamation", 
		"code" => "f12a", 
	],
	[
		"name" => "Exclamation Circle", 
		"icon" => "exclamation-circle", 
		"code" => "f06a", 
	],
	[
		"name" => "Exclamation Triangle", 
		"icon" => "exclamation-triangle", 
		"code" => "f071", 
	],
	[
		"name" => "Expand", 
		"icon" => "expand", 
		"code" => "f065", 
	],
	[
		"name" => "Expand Arrows Alt", 
		"icon" => "expand-arrows-alt", 
		"code" => "f31e", 
	],
	[
		"name" => "Expeditedssl", 
		"icon" => "expeditedssl", 
		"code" => "f23e", 
	],
	[
		"name" => "External Link Alt", 
		"icon" => "external-link-alt", 
		"code" => "f35d", 
	],
	[
		"name" => "External Link Square Alt", 
		"icon" => "external-link-square-alt", 
		"code" => "f360", 
	],
	[
		"name" => "Eye", 
		"icon" => "eye", 
		"code" => "f06e", 
	],
	[
		"name" => "Eye Dropper", 
		"icon" => "eye-dropper", 
		"code" => "f1fb", 
	],
	[
		"name" => "Eye Slash", 
		"icon" => "eye-slash", 
		"code" => "f070", 
	],
	[
		"name" => "Facebook", 
		"icon" => "facebook", 
		"code" => "f09a", 
	],
	[
		"name" => "Facebook F", 
		"icon" => "facebook-f", 
		"code" => "f39e", 
	],
	[
		"name" => "Facebook Messenger", 
		"icon" => "facebook-messenger", 
		"code" => "f39f", 
	],
	[
		"name" => "Facebook Square", 
		"icon" => "facebook-square", 
		"code" => "f082", 
	],
	[
		"name" => "Fast Backward", 
		"icon" => "fast-backward", 
		"code" => "f049", 
	],
	[
		"name" => "Fast Forward", 
		"icon" => "fast-forward", 
		"code" => "f050", 
	],
	[
		"name" => "Fax", 
		"icon" => "fax", 
		"code" => "f1ac", 
	],
	[
		"name" => "Female", 
		"icon" => "female", 
		"code" => "f182", 
	],
	[
		"name" => "Fighter Jet", 
		"icon" => "fighter-jet", 
		"code" => "f0fb", 
	],
	[
		"name" => "File", 
		"icon" => "file", 
		"code" => "f15b", 
	],
	[
		"name" => "File Alt", 
		"icon" => "file-alt", 
		"code" => "f15c", 
	],
	[
		"name" => "File Archive", 
		"icon" => "file-archive", 
		"code" => "f1c6", 
	],
	[
		"name" => "File Audio", 
		"icon" => "file-audio", 
		"code" => "f1c7", 
	],
	[
		"name" => "File Code", 
		"icon" => "file-code", 
		"code" => "f1c9", 
	],
	[
		"name" => "File Excel", 
		"icon" => "file-excel", 
		"code" => "f1c3", 
	],
	[
		"name" => "File Image", 
		"icon" => "file-image", 
		"code" => "f1c5", 
	],
	[
		"name" => "File Pdf", 
		"icon" => "file-pdf", 
		"code" => "f1c1", 
	],
	[
		"name" => "File Powerpoint", 
		"icon" => "file-powerpoint", 
		"code" => "f1c4", 
	],
	[
		"name" => "File Video", 
		"icon" => "file-video", 
		"code" => "f1c8", 
	],
	[
		"name" => "File Word", 
		"icon" => "file-word", 
		"code" => "f1c2", 
	],
	[
		"name" => "Film", 
		"icon" => "film", 
		"code" => "f008", 
	],
	[
		"name" => "Filter", 
		"icon" => "filter", 
		"code" => "f0b0", 
	],
	[
		"name" => "Fire", 
		"icon" => "fire", 
		"code" => "f06d", 
	],
	[
		"name" => "Fire Extinguisher", 
		"icon" => "fire-extinguisher", 
		"code" => "f134", 
	],
	[
		"name" => "Firefox", 
		"icon" => "firefox", 
		"code" => "f269", 
	],
	[
		"name" => "First Aid", 
		"icon" => "first-aid", 
		"code" => "f479", 
	],
	[
		"name" => "First Order", 
		"icon" => "first-order", 
		"code" => "f2b0", 
	],
	[
		"name" => "Firstdraft", 
		"icon" => "firstdraft", 
		"code" => "f3a1", 
	],
	[
		"name" => "Flag", 
		"icon" => "flag", 
		"code" => "f024", 
	],
	[
		"name" => "Flag Checkered", 
		"icon" => "flag-checkered", 
		"code" => "f11e", 
	],
	[
		"name" => "Flask", 
		"icon" => "flask", 
		"code" => "f0c3", 
	],
	[
		"name" => "Flickr", 
		"icon" => "flickr", 
		"code" => "f16e", 
	],
	[
		"name" => "Flipboard", 
		"icon" => "flipboard", 
		"code" => "f44d", 
	],
	[
		"name" => "Fly", 
		"icon" => "fly", 
		"code" => "f417", 
	],
	[
		"name" => "Folder", 
		"icon" => "folder", 
		"code" => "f07b", 
	],
	[
		"name" => "Folder Open", 
		"icon" => "folder-open", 
		"code" => "f07c", 
	],
	[
		"name" => "Font", 
		"icon" => "font", 
		"code" => "f031", 
	],
	[
		"name" => "Font Awesome", 
		"icon" => "font-awesome", 
		"code" => "f2b4", 
	],
	[
		"name" => "Font Awesome Alt", 
		"icon" => "font-awesome-alt", 
		"code" => "f35c", 
	],
	[
		"name" => "Font Awesome Flag", 
		"icon" => "font-awesome-flag", 
		"code" => "f425", 
	],
	[
		"name" => "Fonticons", 
		"icon" => "fonticons", 
		"code" => "f280", 
	],
	[
		"name" => "Fonticons Fi", 
		"icon" => "fonticons-fi", 
		"code" => "f3a2", 
	],
	[
		"name" => "Football Ball", 
		"icon" => "football-ball", 
		"code" => "f44e", 
	],
	[
		"name" => "Fort Awesome", 
		"icon" => "fort-awesome", 
		"code" => "f286", 
	],
	[
		"name" => "Fort Awesome Alt", 
		"icon" => "fort-awesome-alt", 
		"code" => "f3a3", 
	],
	[
		"name" => "Forumbee", 
		"icon" => "forumbee", 
		"code" => "f211", 
	],
	[
		"name" => "Forward", 
		"icon" => "forward", 
		"code" => "f04e", 
	],
	[
		"name" => "Foursquare", 
		"icon" => "foursquare", 
		"code" => "f180", 
	],
	[
		"name" => "Free Code Camp", 
		"icon" => "free-code-camp", 
		"code" => "f2c5", 
	],
	[
		"name" => "Freebsd", 
		"icon" => "freebsd", 
		"code" => "f3a4", 
	],
	[
		"name" => "Frown", 
		"icon" => "frown", 
		"code" => "f119", 
	],
	[
		"name" => "Futbol", 
		"icon" => "futbol", 
		"code" => "f1e3", 
	],
	[
		"name" => "Gamepad", 
		"icon" => "gamepad", 
		"code" => "f11b", 
	],
	[
		"name" => "Gavel", 
		"icon" => "gavel", 
		"code" => "f0e3", 
	],
	[
		"name" => "Gem", 
		"icon" => "gem", 
		"code" => "f3a5", 
	],
	[
		"name" => "Genderless", 
		"icon" => "genderless", 
		"code" => "f22d", 
	],
	[
		"name" => "Get Pocket", 
		"icon" => "get-pocket", 
		"code" => "f265", 
	],
	[
		"name" => "Gg", 
		"icon" => "gg", 
		"code" => "f260", 
	],
	[
		"name" => "Gg Circle", 
		"icon" => "gg-circle", 
		"code" => "f261", 
	],
	[
		"name" => "Gift", 
		"icon" => "gift", 
		"code" => "f06b", 
	],
	[
		"name" => "Git", 
		"icon" => "git", 
		"code" => "f1d3", 
	],
	[
		"name" => "Git Square", 
		"icon" => "git-square", 
		"code" => "f1d2", 
	],
	[
		"name" => "Github", 
		"icon" => "github", 
		"code" => "f09b", 
	],
	[
		"name" => "Github Alt", 
		"icon" => "github-alt", 
		"code" => "f113", 
	],
	[
		"name" => "Github Square", 
		"icon" => "github-square", 
		"code" => "f092", 
	],
	[
		"name" => "Gitkraken", 
		"icon" => "gitkraken", 
		"code" => "f3a6", 
	],
	[
		"name" => "Gitlab", 
		"icon" => "gitlab", 
		"code" => "f296", 
	],
	[
		"name" => "Gitter", 
		"icon" => "gitter", 
		"code" => "f426", 
	],
	[
		"name" => "Glass Martini", 
		"icon" => "glass-martini", 
		"code" => "f000", 
	],
	[
		"name" => "Glide", 
		"icon" => "glide", 
		"code" => "f2a5", 
	],
	[
		"name" => "Glide G", 
		"icon" => "glide-g", 
		"code" => "f2a6", 
	],
	[
		"name" => "Globe", 
		"icon" => "globe", 
		"code" => "f0ac", 
	],
	[
		"name" => "Gofore", 
		"icon" => "gofore", 
		"code" => "f3a7", 
	],
	[
		"name" => "Golf Ball", 
		"icon" => "golf-ball", 
		"code" => "f450", 
	],
	[
		"name" => "Goodreads", 
		"icon" => "goodreads", 
		"code" => "f3a8", 
	],
	[
		"name" => "Goodreads G", 
		"icon" => "goodreads-g", 
		"code" => "f3a9", 
	],
	[
		"name" => "Google", 
		"icon" => "google", 
		"code" => "f1a0", 
	],
	[
		"name" => "Google Drive", 
		"icon" => "google-drive", 
		"code" => "f3aa", 
	],
	[
		"name" => "Google Play", 
		"icon" => "google-play", 
		"code" => "f3ab", 
	],
	[
		"name" => "Google Plus", 
		"icon" => "google-plus", 
		"code" => "f2b3", 
	],
	[
		"name" => "Google Plus G", 
		"icon" => "google-plus-g", 
		"code" => "f0d5", 
	],
	[
		"name" => "Google Plus Square", 
		"icon" => "google-plus-square", 
		"code" => "f0d4", 
	],
	[
		"name" => "Google Wallet", 
		"icon" => "google-wallet", 
		"code" => "f1ee", 
	],
	[
		"name" => "Graduation Cap", 
		"icon" => "graduation-cap", 
		"code" => "f19d", 
	],
	[
		"name" => "Gratipay", 
		"icon" => "gratipay", 
		"code" => "f184", 
	],
	[
		"name" => "Grav", 
		"icon" => "grav", 
		"code" => "f2d6", 
	],
	[
		"name" => "Gripfire", 
		"icon" => "gripfire", 
		"code" => "f3ac", 
	],
	[
		"name" => "Grunt", 
		"icon" => "grunt", 
		"code" => "f3ad", 
	],
	[
		"name" => "Gulp", 
		"icon" => "gulp", 
		"code" => "f3ae", 
	],
	[
		"name" => "H Square", 
		"icon" => "h-square", 
		"code" => "f0fd", 
	],
	[
		"name" => "Hacker News", 
		"icon" => "hacker-news", 
		"code" => "f1d4", 
	],
	[
		"name" => "Hacker News Square", 
		"icon" => "hacker-news-square", 
		"code" => "f3af", 
	],
	[
		"name" => "Hand Lizard", 
		"icon" => "hand-lizard", 
		"code" => "f258", 
	],
	[
		"name" => "Hand Paper", 
		"icon" => "hand-paper", 
		"code" => "f256", 
	],
	[
		"name" => "Hand Peace", 
		"icon" => "hand-peace", 
		"code" => "f25b", 
	],
	[
		"name" => "Hand Point Down", 
		"icon" => "hand-point-down", 
		"code" => "f0a7", 
	],
	[
		"name" => "Hand Point Left", 
		"icon" => "hand-point-left", 
		"code" => "f0a5", 
	],
	[
		"name" => "Hand Point Right", 
		"icon" => "hand-point-right", 
		"code" => "f0a4", 
	],
	[
		"name" => "Hand Point Up", 
		"icon" => "hand-point-up", 
		"code" => "f0a6", 
	],
	[
		"name" => "Hand Pointer", 
		"icon" => "hand-pointer", 
		"code" => "f25a", 
	],
	[
		"name" => "Hand Rock", 
		"icon" => "hand-rock", 
		"code" => "f255", 
	],
	[
		"name" => "Hand Scissors", 
		"icon" => "hand-scissors", 
		"code" => "f257", 
	],
	[
		"name" => "Hand Spock", 
		"icon" => "hand-spock", 
		"code" => "f259", 
	],
	[
		"name" => "Handshake", 
		"icon" => "handshake", 
		"code" => "f2b5", 
	],
	[
		"name" => "Hashtag", 
		"icon" => "hashtag", 
		"code" => "f292", 
	],
	[
		"name" => "Hdd", 
		"icon" => "hdd", 
		"code" => "f0a0", 
	],
	[
		"name" => "Heading", 
		"icon" => "heading", 
		"code" => "f1dc", 
	],
	[
		"name" => "Headphones", 
		"icon" => "headphones", 
		"code" => "f025", 
	],
	[
		"name" => "Heart", 
		"icon" => "heart", 
		"code" => "f004", 
	],
	[
		"name" => "Heartbeat", 
		"icon" => "heartbeat", 
		"code" => "f21e", 
	],
	[
		"name" => "Hips", 
		"icon" => "hips", 
		"code" => "f452", 
	],
	[
		"name" => "Hire A Helper", 
		"icon" => "hire-a-helper", 
		"code" => "f3b0", 
	],
	[
		"name" => "History", 
		"icon" => "history", 
		"code" => "f1da", 
	],
	[
		"name" => "Hockey Puck", 
		"icon" => "hockey-puck", 
		"code" => "f453", 
	],
	[
		"name" => "Home", 
		"icon" => "home", 
		"code" => "f015", 
	],
	[
		"name" => "Hooli", 
		"icon" => "hooli", 
		"code" => "f427", 
	],
	[
		"name" => "Hospital", 
		"icon" => "hospital", 
		"code" => "f0f8", 
	],
	[
		"name" => "Hospital Symbol", 
		"icon" => "hospital-symbol", 
		"code" => "f47e", 
	],
	[
		"name" => "Hotjar", 
		"icon" => "hotjar", 
		"code" => "f3b1", 
	],
	[
		"name" => "Hourglass", 
		"icon" => "hourglass", 
		"code" => "f254", 
	],
	[
		"name" => "Hourglass End", 
		"icon" => "hourglass-end", 
		"code" => "f253", 
	],
	[
		"name" => "Hourglass Half", 
		"icon" => "hourglass-half", 
		"code" => "f252", 
	],
	[
		"name" => "Hourglass Start", 
		"icon" => "hourglass-start", 
		"code" => "f251", 
	],
	[
		"name" => "Houzz", 
		"icon" => "houzz", 
		"code" => "f27c", 
	],
	[
		"name" => "Html5", 
		"icon" => "html5", 
		"code" => "f13b", 
	],
	[
		"name" => "Hubspot", 
		"icon" => "hubspot", 
		"code" => "f3b2", 
	],
	[
		"name" => "I Cursor", 
		"icon" => "i-cursor", 
		"code" => "f246", 
	],
	[
		"name" => "Id Badge", 
		"icon" => "id-badge", 
		"code" => "f2c1", 
	],
	[
		"name" => "Id Card", 
		"icon" => "id-card", 
		"code" => "f2c2", 
	],
	[
		"name" => "Image", 
		"icon" => "image", 
		"code" => "f03e", 
	],
	[
		"name" => "Images", 
		"icon" => "images", 
		"code" => "f302", 
	],
	[
		"name" => "Imdb", 
		"icon" => "imdb", 
		"code" => "f2d8", 
	],
	[
		"name" => "Inbox", 
		"icon" => "inbox", 
		"code" => "f01c", 
	],
	[
		"name" => "Indent", 
		"icon" => "indent", 
		"code" => "f03c", 
	],
	[
		"name" => "Industry", 
		"icon" => "industry", 
		"code" => "f275", 
	],
	[
		"name" => "Info", 
		"icon" => "info", 
		"code" => "f129", 
	],
	[
		"name" => "Info Circle", 
		"icon" => "info-circle", 
		"code" => "f05a", 
	],
	[
		"name" => "Instagram", 
		"icon" => "instagram", 
		"code" => "f16d", 
	],
	[
		"name" => "Internet Explorer", 
		"icon" => "internet-explorer", 
		"code" => "f26b", 
	],
	[
		"name" => "Ioxhost", 
		"icon" => "ioxhost", 
		"code" => "f208", 
	],
	[
		"name" => "Italic", 
		"icon" => "italic", 
		"code" => "f033", 
	],
	[
		"name" => "Itunes", 
		"icon" => "itunes", 
		"code" => "f3b4", 
	],
	[
		"name" => "Itunes Note", 
		"icon" => "itunes-note", 
		"code" => "f3b5", 
	],
	[
		"name" => "Jenkins", 
		"icon" => "jenkins", 
		"code" => "f3b6", 
	],
	[
		"name" => "Joget", 
		"icon" => "joget", 
		"code" => "f3b7", 
	],
	[
		"name" => "Joomla", 
		"icon" => "joomla", 
		"code" => "f1aa", 
	],
	[
		"name" => "Js", 
		"icon" => "js", 
		"code" => "f3b8", 
	],
	[
		"name" => "Js Square", 
		"icon" => "js-square", 
		"code" => "f3b9", 
	],
	[
		"name" => "Jsfiddle", 
		"icon" => "jsfiddle", 
		"code" => "f1cc", 
	],
	[
		"name" => "Key", 
		"icon" => "key", 
		"code" => "f084", 
	],
	[
		"name" => "Keyboard", 
		"icon" => "keyboard", 
		"code" => "f11c", 
	],
	[
		"name" => "Keycdn", 
		"icon" => "keycdn", 
		"code" => "f3ba", 
	],
	[
		"name" => "Kickstarter", 
		"icon" => "kickstarter", 
		"code" => "f3bb", 
	],
	[
		"name" => "Kickstarter K", 
		"icon" => "kickstarter-k", 
		"code" => "f3bc", 
	],
	[
		"name" => "Korvue", 
		"icon" => "korvue", 
		"code" => "f42f", 
	],
	[
		"name" => "Language", 
		"icon" => "language", 
		"code" => "f1ab", 
	],
	[
		"name" => "Laptop", 
		"icon" => "laptop", 
		"code" => "f109", 
	],
	[
		"name" => "Laravel", 
		"icon" => "laravel", 
		"code" => "f3bd", 
	],
	[
		"name" => "Lastfm", 
		"icon" => "lastfm", 
		"code" => "f202", 
	],
	[
		"name" => "Lastfm Square", 
		"icon" => "lastfm-square", 
		"code" => "f203", 
	],
	[
		"name" => "Leaf", 
		"icon" => "leaf", 
		"code" => "f06c", 
	],
	[
		"name" => "Leanpub", 
		"icon" => "leanpub", 
		"code" => "f212", 
	],
	[
		"name" => "Lemon", 
		"icon" => "lemon", 
		"code" => "f094", 
	],
	[
		"name" => "Less", 
		"icon" => "less", 
		"code" => "f41d", 
	],
	[
		"name" => "Level Down Alt", 
		"icon" => "level-down-alt", 
		"code" => "f3be", 
	],
	[
		"name" => "Level Up Alt", 
		"icon" => "level-up-alt", 
		"code" => "f3bf", 
	],
	[
		"name" => "Life Ring", 
		"icon" => "life-ring", 
		"code" => "f1cd", 
	],
	[
		"name" => "Lightbulb", 
		"icon" => "lightbulb", 
		"code" => "f0eb", 
	],
	[
		"name" => "Line", 
		"icon" => "line", 
		"code" => "f3c0", 
	],
	[
		"name" => "Link", 
		"icon" => "link", 
		"code" => "f0c1", 
	],
	[
		"name" => "Linkedin", 
		"icon" => "linkedin", 
		"code" => "f08c", 
	],
	[
		"name" => "Linkedin In", 
		"icon" => "linkedin-in", 
		"code" => "f0e1", 
	],
	[
		"name" => "Linode", 
		"icon" => "linode", 
		"code" => "f2b8", 
	],
	[
		"name" => "Linux", 
		"icon" => "linux", 
		"code" => "f17c", 
	],
	[
		"name" => "Lira Sign", 
		"icon" => "lira-sign", 
		"code" => "f195", 
	],
	[
		"name" => "List", 
		"icon" => "list", 
		"code" => "f03a", 
	],
	[
		"name" => "List Alt", 
		"icon" => "list-alt", 
		"code" => "f022", 
	],
	[
		"name" => "List Ol", 
		"icon" => "list-ol", 
		"code" => "f0cb", 
	],
	[
		"name" => "List Ul", 
		"icon" => "list-ul", 
		"code" => "f0ca", 
	],
	[
		"name" => "Location Arrow", 
		"icon" => "location-arrow", 
		"code" => "f124", 
	],
	[
		"name" => "Lock", 
		"icon" => "lock", 
		"code" => "f023", 
	],
	[
		"name" => "Lock Open", 
		"icon" => "lock-open", 
		"code" => "f3c1", 
	],
	[
		"name" => "Long Arrow Alt Down", 
		"icon" => "long-arrow-alt-down", 
		"code" => "f309", 
	],
	[
		"name" => "Long Arrow Alt Left", 
		"icon" => "long-arrow-alt-left", 
		"code" => "f30a", 
	],
	[
		"name" => "Long Arrow Alt Right", 
		"icon" => "long-arrow-alt-right", 
		"code" => "f30b", 
	],
	[
		"name" => "Long Arrow Alt Up", 
		"icon" => "long-arrow-alt-up", 
		"code" => "f30c", 
	],
	[
		"name" => "Low Vision", 
		"icon" => "low-vision", 
		"code" => "f2a8", 
	],
	[
		"name" => "Lyft", 
		"icon" => "lyft", 
		"code" => "f3c3", 
	],
	[
		"name" => "Magento", 
		"icon" => "magento", 
		"code" => "f3c4", 
	],
	[
		"name" => "Magic", 
		"icon" => "magic", 
		"code" => "f0d0", 
	],
	[
		"name" => "Magnet", 
		"icon" => "magnet", 
		"code" => "f076", 
	],
	[
		"name" => "Male", 
		"icon" => "male", 
		"code" => "f183", 
	],
	[
		"name" => "Map", 
		"icon" => "map", 
		"code" => "f279", 
	],
	[
		"name" => "Map Marker", 
		"icon" => "map-marker", 
		"code" => "f041", 
	],
	[
		"name" => "Map Marker Alt", 
		"icon" => "map-marker-alt", 
		"code" => "f3c5", 
	],
	[
		"name" => "Map Pin", 
		"icon" => "map-pin", 
		"code" => "f276", 
	],
	[
		"name" => "Map Signs", 
		"icon" => "map-signs", 
		"code" => "f277", 
	],
	[
		"name" => "Mars", 
		"icon" => "mars", 
		"code" => "f222", 
	],
	[
		"name" => "Mars Double", 
		"icon" => "mars-double", 
		"code" => "f227", 
	],
	[
		"name" => "Mars Stroke", 
		"icon" => "mars-stroke", 
		"code" => "f229", 
	],
	[
		"name" => "Mars Stroke H", 
		"icon" => "mars-stroke-h", 
		"code" => "f22b", 
	],
	[
		"name" => "Mars Stroke V", 
		"icon" => "mars-stroke-v", 
		"code" => "f22a", 
	],
	[
		"name" => "Maxcdn", 
		"icon" => "maxcdn", 
		"code" => "f136", 
	],
	[
		"name" => "Medapps", 
		"icon" => "medapps", 
		"code" => "f3c6", 
	],
	[
		"name" => "Medium", 
		"icon" => "medium", 
		"code" => "f23a", 
	],
	[
		"name" => "Medium M", 
		"icon" => "medium-m", 
		"code" => "f3c7", 
	],
	[
		"name" => "Medkit", 
		"icon" => "medkit", 
		"code" => "f0fa", 
	],
	[
		"name" => "Medrt", 
		"icon" => "medrt", 
		"code" => "f3c8", 
	],
	[
		"name" => "Meetup", 
		"icon" => "meetup", 
		"code" => "f2e0", 
	],
	[
		"name" => "Meh", 
		"icon" => "meh", 
		"code" => "f11a", 
	],
	[
		"name" => "Mercury", 
		"icon" => "mercury", 
		"code" => "f223", 
	],
	[
		"name" => "Microchip", 
		"icon" => "microchip", 
		"code" => "f2db", 
	],
	[
		"name" => "Microphone", 
		"icon" => "microphone", 
		"code" => "f130", 
	],
	[
		"name" => "Microphone Slash", 
		"icon" => "microphone-slash", 
		"code" => "f131", 
	],
	[
		"name" => "Microsoft", 
		"icon" => "microsoft", 
		"code" => "f3ca", 
	],
	[
		"name" => "Minus", 
		"icon" => "minus", 
		"code" => "f068", 
	],
	[
		"name" => "Minus Circle", 
		"icon" => "minus-circle", 
		"code" => "f056", 
	],
	[
		"name" => "Minus Square", 
		"icon" => "minus-square", 
		"code" => "f146", 
	],
	[
		"name" => "Mix", 
		"icon" => "mix", 
		"code" => "f3cb", 
	],
	[
		"name" => "Mixcloud", 
		"icon" => "mixcloud", 
		"code" => "f289", 
	],
	[
		"name" => "Mizuni", 
		"icon" => "mizuni", 
		"code" => "f3cc", 
	],
	[
		"name" => "Mobile", 
		"icon" => "mobile", 
		"code" => "f10b", 
	],
	[
		"name" => "Mobile Alt", 
		"icon" => "mobile-alt", 
		"code" => "f3cd", 
	],
	[
		"name" => "Modx", 
		"icon" => "modx", 
		"code" => "f285", 
	],
	[
		"name" => "Monero", 
		"icon" => "monero", 
		"code" => "f3d0", 
	],
	[
		"name" => "Money Bill Alt", 
		"icon" => "money-bill-alt", 
		"code" => "f3d1", 
	],
	[
		"name" => "Moon", 
		"icon" => "moon", 
		"code" => "f186", 
	],
	[
		"name" => "Motorcycle", 
		"icon" => "motorcycle", 
		"code" => "f21c", 
	],
	[
		"name" => "Mouse Pointer", 
		"icon" => "mouse-pointer", 
		"code" => "f245", 
	],
	[
		"name" => "Music", 
		"icon" => "music", 
		"code" => "f001", 
	],
	[
		"name" => "Napster", 
		"icon" => "napster", 
		"code" => "f3d2", 
	],
	[
		"name" => "Neuter", 
		"icon" => "neuter", 
		"code" => "f22c", 
	],
	[
		"name" => "Newspaper", 
		"icon" => "newspaper", 
		"code" => "f1ea", 
	],
	[
		"name" => "Nintendo Switch", 
		"icon" => "nintendo-switch", 
		"code" => "f418", 
	],
	[
		"name" => "Node", 
		"icon" => "node", 
		"code" => "f419", 
	],
	[
		"name" => "Node Js", 
		"icon" => "node-js", 
		"code" => "f3d3", 
	],
	[
		"name" => "Npm", 
		"icon" => "npm", 
		"code" => "f3d4", 
	],
	[
		"name" => "Ns8", 
		"icon" => "ns8", 
		"code" => "f3d5", 
	],
	[
		"name" => "Nutritionix", 
		"icon" => "nutritionix", 
		"code" => "f3d6", 
	],
	[
		"name" => "Object Group", 
		"icon" => "object-group", 
		"code" => "f247", 
	],
	[
		"name" => "Object Ungroup", 
		"icon" => "object-ungroup", 
		"code" => "f248", 
	],
	[
		"name" => "Odnoklassniki", 
		"icon" => "odnoklassniki", 
		"code" => "f263", 
	],
	[
		"name" => "Odnoklassniki Square", 
		"icon" => "odnoklassniki-square", 
		"code" => "f264", 
	],
	[
		"name" => "Opencart", 
		"icon" => "opencart", 
		"code" => "f23d", 
	],
	[
		"name" => "Openid", 
		"icon" => "openid", 
		"code" => "f19b", 
	],
	[
		"name" => "Opera", 
		"icon" => "opera", 
		"code" => "f26a", 
	],
	[
		"name" => "Optin Monster", 
		"icon" => "optin-monster", 
		"code" => "f23c", 
	],
	[
		"name" => "Osi", 
		"icon" => "osi", 
		"code" => "f41a", 
	],
	[
		"name" => "Outdent", 
		"icon" => "outdent", 
		"code" => "f03b", 
	],
	[
		"name" => "Page4", 
		"icon" => "page4", 
		"code" => "f3d7", 
	],
	[
		"name" => "Pagelines", 
		"icon" => "pagelines", 
		"code" => "f18c", 
	],
	[
		"name" => "Paint Brush", 
		"icon" => "paint-brush", 
		"code" => "f1fc", 
	],
	[
		"name" => "Palfed", 
		"icon" => "palfed", 
		"code" => "f3d8", 
	],
	[
		"name" => "Pallet", 
		"icon" => "pallet", 
		"code" => "f482", 
	],
	[
		"name" => "Paper Plane", 
		"icon" => "paper-plane", 
		"code" => "f1d8", 
	],
	[
		"name" => "Paperclip", 
		"icon" => "paperclip", 
		"code" => "f0c6", 
	],
	[
		"name" => "Paragraph", 
		"icon" => "paragraph", 
		"code" => "f1dd", 
	],
	[
		"name" => "Paste", 
		"icon" => "paste", 
		"code" => "f0ea", 
	],
	[
		"name" => "Patreon", 
		"icon" => "patreon", 
		"code" => "f3d9", 
	],
	[
		"name" => "Pause", 
		"icon" => "pause", 
		"code" => "f04c", 
	],
	[
		"name" => "Pause Circle", 
		"icon" => "pause-circle", 
		"code" => "f28b", 
	],
	[
		"name" => "Paw", 
		"icon" => "paw", 
		"code" => "f1b0", 
	],
	[
		"name" => "Paypal", 
		"icon" => "paypal", 
		"code" => "f1ed", 
	],
	[
		"name" => "Pen Square", 
		"icon" => "pen-square", 
		"code" => "f14b", 
	],
	[
		"name" => "Pencil Alt", 
		"icon" => "pencil-alt", 
		"code" => "f303", 
	],
	[
		"name" => "Percent", 
		"icon" => "percent", 
		"code" => "f295", 
	],
	[
		"name" => "Periscope", 
		"icon" => "periscope", 
		"code" => "f3da", 
	],
	[
		"name" => "Phabricator", 
		"icon" => "phabricator", 
		"code" => "f3db", 
	],
	[
		"name" => "Phoenix Framework", 
		"icon" => "phoenix-framework", 
		"code" => "f3dc", 
	],
	[
		"name" => "Phone", 
		"icon" => "phone", 
		"code" => "f095", 
	],
	[
		"name" => "Phone Square", 
		"icon" => "phone-square", 
		"code" => "f098", 
	],
	[
		"name" => "Phone Volume", 
		"icon" => "phone-volume", 
		"code" => "f2a0", 
	],
	[
		"name" => "Php", 
		"icon" => "php", 
		"code" => "f457", 
	],
	[
		"name" => "Pied Piper", 
		"icon" => "pied-piper", 
		"code" => "f2ae", 
	],
	[
		"name" => "Pied Piper Alt", 
		"icon" => "pied-piper-alt", 
		"code" => "f1a8", 
	],
	[
		"name" => "Pied Piper Pp", 
		"icon" => "pied-piper-pp", 
		"code" => "f1a7", 
	],
	[
		"name" => "Pills", 
		"icon" => "pills", 
		"code" => "f484", 
	],
	[
		"name" => "Pinterest", 
		"icon" => "pinterest", 
		"code" => "f0d2", 
	],
	[
		"name" => "Pinterest P", 
		"icon" => "pinterest-p", 
		"code" => "f231", 
	],
	[
		"name" => "Pinterest Square", 
		"icon" => "pinterest-square", 
		"code" => "f0d3", 
	],
	[
		"name" => "Plane", 
		"icon" => "plane", 
		"code" => "f072", 
	],
	[
		"name" => "Play", 
		"icon" => "play", 
		"code" => "f04b", 
	],
	[
		"name" => "Play Circle", 
		"icon" => "play-circle", 
		"code" => "f144", 
	],
	[
		"name" => "Playstation", 
		"icon" => "playstation", 
		"code" => "f3df", 
	],
	[
		"name" => "Plug", 
		"icon" => "plug", 
		"code" => "f1e6", 
	],
	[
		"name" => "Plus", 
		"icon" => "plus", 
		"code" => "f067", 
	],
	[
		"name" => "Plus Circle", 
		"icon" => "plus-circle", 
		"code" => "f055", 
	],
	[
		"name" => "Plus Square", 
		"icon" => "plus-square", 
		"code" => "f0fe", 
	],
	[
		"name" => "Podcast", 
		"icon" => "podcast", 
		"code" => "f2ce", 
	],
	[
		"name" => "Pound Sign", 
		"icon" => "pound-sign", 
		"code" => "f154", 
	],
	[
		"name" => "Power Off", 
		"icon" => "power-off", 
		"code" => "f011", 
	],
	[
		"name" => "Print", 
		"icon" => "print", 
		"code" => "f02f", 
	],
	[
		"name" => "Product Hunt", 
		"icon" => "product-hunt", 
		"code" => "f288", 
	],
	[
		"name" => "Pushed", 
		"icon" => "pushed", 
		"code" => "f3e1", 
	],
	[
		"name" => "Puzzle Piece", 
		"icon" => "puzzle-piece", 
		"code" => "f12e", 
	],
	[
		"name" => "Python", 
		"icon" => "python", 
		"code" => "f3e2", 
	],
	[
		"name" => "Qq", 
		"icon" => "qq", 
		"code" => "f1d6", 
	],
	[
		"name" => "Qrcode", 
		"icon" => "qrcode", 
		"code" => "f029", 
	],
	[
		"name" => "Question", 
		"icon" => "question", 
		"code" => "f128", 
	],
	[
		"name" => "Question Circle", 
		"icon" => "question-circle", 
		"code" => "f059", 
	],
	[
		"name" => "Quidditch", 
		"icon" => "quidditch", 
		"code" => "f458", 
	],
	[
		"name" => "Quinscape", 
		"icon" => "quinscape", 
		"code" => "f459", 
	],
	[
		"name" => "Quora", 
		"icon" => "quora", 
		"code" => "f2c4", 
	],
	[
		"name" => "Quote Left", 
		"icon" => "quote-left", 
		"code" => "f10d", 
	],
	[
		"name" => "Quote Right", 
		"icon" => "quote-right", 
		"code" => "f10e", 
	],
	[
		"name" => "Random", 
		"icon" => "random", 
		"code" => "f074", 
	],
	[
		"name" => "Ravelry", 
		"icon" => "ravelry", 
		"code" => "f2d9", 
	],
	[
		"name" => "React", 
		"icon" => "react", 
		"code" => "f41b", 
	],
	[
		"name" => "Rebel", 
		"icon" => "rebel", 
		"code" => "f1d0", 
	],
	[
		"name" => "Recycle", 
		"icon" => "recycle", 
		"code" => "f1b8", 
	],
	[
		"name" => "Red River", 
		"icon" => "red-river", 
		"code" => "f3e3", 
	],
	[
		"name" => "Reddit", 
		"icon" => "reddit", 
		"code" => "f1a1", 
	],
	[
		"name" => "Reddit Alien", 
		"icon" => "reddit-alien", 
		"code" => "f281", 
	],
	[
		"name" => "Reddit Square", 
		"icon" => "reddit-square", 
		"code" => "f1a2", 
	],
	[
		"name" => "Redo", 
		"icon" => "redo", 
		"code" => "f01e", 
	],
	[
		"name" => "Redo Alt", 
		"icon" => "redo-alt", 
		"code" => "f2f9", 
	],
	[
		"name" => "Registered", 
		"icon" => "registered", 
		"code" => "f25d", 
	],
	[
		"name" => "Rendact", 
		"icon" => "rendact", 
		"code" => "f3e4", 
	],
	[
		"name" => "Renren", 
		"icon" => "renren", 
		"code" => "f18b", 
	],
	[
		"name" => "Reply", 
		"icon" => "reply", 
		"code" => "f3e5", 
	],
	[
		"name" => "Reply All", 
		"icon" => "reply-all", 
		"code" => "f122", 
	],
	[
		"name" => "Replyd", 
		"icon" => "replyd", 
		"code" => "f3e6", 
	],
	[
		"name" => "Resolving", 
		"icon" => "resolving", 
		"code" => "f3e7", 
	],
	[
		"name" => "Retweet", 
		"icon" => "retweet", 
		"code" => "f079", 
	],
	[
		"name" => "Road", 
		"icon" => "road", 
		"code" => "f018", 
	],
	[
		"name" => "Rocket", 
		"icon" => "rocket", 
		"code" => "f135", 
	],
	[
		"name" => "Rocketchat", 
		"icon" => "rocketchat", 
		"code" => "f3e8", 
	],
	[
		"name" => "Rockrms", 
		"icon" => "rockrms", 
		"code" => "f3e9", 
	],
	[
		"name" => "Rss", 
		"icon" => "rss", 
		"code" => "f09e", 
	],
	[
		"name" => "Rss Square", 
		"icon" => "rss-square", 
		"code" => "f143", 
	],
	[
		"name" => "Ruble Sign", 
		"icon" => "ruble-sign", 
		"code" => "f158", 
	],
	[
		"name" => "Rupee Sign", 
		"icon" => "rupee-sign", 
		"code" => "f156", 
	],
	[
		"name" => "Safari", 
		"icon" => "safari", 
		"code" => "f267", 
	],
	[
		"name" => "Sass", 
		"icon" => "sass", 
		"code" => "f41e", 
	],
	[
		"name" => "Save", 
		"icon" => "save", 
		"code" => "f0c7", 
	],
	[
		"name" => "Schlix", 
		"icon" => "schlix", 
		"code" => "f3ea", 
	],
	[
		"name" => "Scribd", 
		"icon" => "scribd", 
		"code" => "f28a", 
	],
	[
		"name" => "Search", 
		"icon" => "search", 
		"code" => "f002", 
	],
	[
		"name" => "Search Minus", 
		"icon" => "search-minus", 
		"code" => "f010", 
	],
	[
		"name" => "Search Plus", 
		"icon" => "search-plus", 
		"code" => "f00e", 
	],
	[
		"name" => "Searchengin", 
		"icon" => "searchengin", 
		"code" => "f3eb", 
	],
	[
		"name" => "Sellcast", 
		"icon" => "sellcast", 
		"code" => "f2da", 
	],
	[
		"name" => "Sellsy", 
		"icon" => "sellsy", 
		"code" => "f213", 
	],
	[
		"name" => "Server", 
		"icon" => "server", 
		"code" => "f233", 
	],
	[
		"name" => "Servicestack", 
		"icon" => "servicestack", 
		"code" => "f3ec", 
	],
	[
		"name" => "Share", 
		"icon" => "share", 
		"code" => "f064", 
	],
	[
		"name" => "Share Alt", 
		"icon" => "share-alt", 
		"code" => "f1e0", 
	],
	[
		"name" => "Share Alt Square", 
		"icon" => "share-alt-square", 
		"code" => "f1e1", 
	],
	[
		"name" => "Share Square", 
		"icon" => "share-square", 
		"code" => "f14d", 
	],
	[
		"name" => "Shekel Sign", 
		"icon" => "shekel-sign", 
		"code" => "f20b", 
	],
	[
		"name" => "Shield Alt", 
		"icon" => "shield-alt", 
		"code" => "f3ed", 
	],
	[
		"name" => "Ship", 
		"icon" => "ship", 
		"code" => "f21a", 
	],
	[
		"name" => "Shipping Fast", 
		"icon" => "shipping-fast", 
		"code" => "f48b", 
	],
	[
		"name" => "Shirtsinbulk", 
		"icon" => "shirtsinbulk", 
		"code" => "f214", 
	],
	[
		"name" => "Shopping Bag", 
		"icon" => "shopping-bag", 
		"code" => "f290", 
	],
	[
		"name" => "Shopping Basket", 
		"icon" => "shopping-basket", 
		"code" => "f291", 
	],
	[
		"name" => "Shopping Cart", 
		"icon" => "shopping-cart", 
		"code" => "f07a", 
	],
	[
		"name" => "Shower", 
		"icon" => "shower", 
		"code" => "f2cc", 
	],
	[
		"name" => "Sign In Alt", 
		"icon" => "sign-in-alt", 
		"code" => "f2f6", 
	],
	[
		"name" => "Sign Language", 
		"icon" => "sign-language", 
		"code" => "f2a7", 
	],
	[
		"name" => "Sign Out Alt", 
		"icon" => "sign-out-alt", 
		"code" => "f2f5", 
	],
	[
		"name" => "Signal", 
		"icon" => "signal", 
		"code" => "f012", 
	],
	[
		"name" => "Simplybuilt", 
		"icon" => "simplybuilt", 
		"code" => "f215", 
	],
	[
		"name" => "Sistrix", 
		"icon" => "sistrix", 
		"code" => "f3ee", 
	],
	[
		"name" => "Sitemap", 
		"icon" => "sitemap", 
		"code" => "f0e8", 
	],
	[
		"name" => "Skyatlas", 
		"icon" => "skyatlas", 
		"code" => "f216", 
	],
	[
		"name" => "Skype", 
		"icon" => "skype", 
		"code" => "f17e", 
	],
	[
		"name" => "Slack", 
		"icon" => "slack", 
		"code" => "f198", 
	],
	[
		"name" => "Slack Hash", 
		"icon" => "slack-hash", 
		"code" => "f3ef", 
	],
	[
		"name" => "Sliders H", 
		"icon" => "sliders-h", 
		"code" => "f1de", 
	],
	[
		"name" => "Slideshare", 
		"icon" => "slideshare", 
		"code" => "f1e7", 
	],
	[
		"name" => "Smile", 
		"icon" => "smile", 
		"code" => "f118", 
	],
	[
		"name" => "Snapchat", 
		"icon" => "snapchat", 
		"code" => "f2ab", 
	],
	[
		"name" => "Snapchat Ghost", 
		"icon" => "snapchat-ghost", 
		"code" => "f2ac", 
	],
	[
		"name" => "Snapchat Square", 
		"icon" => "snapchat-square", 
		"code" => "f2ad", 
	],
	[
		"name" => "Snowflake", 
		"icon" => "snowflake", 
		"code" => "f2dc", 
	],
	[
		"name" => "Sort", 
		"icon" => "sort", 
		"code" => "f0dc", 
	],
	[
		"name" => "Sort Alpha Down", 
		"icon" => "sort-alpha-down", 
		"code" => "f15d", 
	],
	[
		"name" => "Sort Alpha Up", 
		"icon" => "sort-alpha-up", 
		"code" => "f15e", 
	],
	[
		"name" => "Sort Amount Down", 
		"icon" => "sort-amount-down", 
		"code" => "f160", 
	],
	[
		"name" => "Sort Amount Up", 
		"icon" => "sort-amount-up", 
		"code" => "f161", 
	],
	[
		"name" => "Sort Down", 
		"icon" => "sort-down", 
		"code" => "f0dd", 
	],
	[
		"name" => "Sort Numeric Down", 
		"icon" => "sort-numeric-down", 
		"code" => "f162", 
	],
	[
		"name" => "Sort Numeric Up", 
		"icon" => "sort-numeric-up", 
		"code" => "f163", 
	],
	[
		"name" => "Sort Up", 
		"icon" => "sort-up", 
		"code" => "f0de", 
	],
	[
		"name" => "Soundcloud", 
		"icon" => "soundcloud", 
		"code" => "f1be", 
	],
	[
		"name" => "Space Shuttle", 
		"icon" => "space-shuttle", 
		"code" => "f197", 
	],
	[
		"name" => "Speakap", 
		"icon" => "speakap", 
		"code" => "f3f3", 
	],
	[
		"name" => "Spinner", 
		"icon" => "spinner", 
		"code" => "f110", 
	],
	[
		"name" => "Spotify", 
		"icon" => "spotify", 
		"code" => "f1bc", 
	],
	[
		"name" => "Square", 
		"icon" => "square", 
		"code" => "f0c8", 
	],
	[
		"name" => "Square Full", 
		"icon" => "square-full", 
		"code" => "f45c", 
	],
	[
		"name" => "Stack Exchange", 
		"icon" => "stack-exchange", 
		"code" => "f18d", 
	],
	[
		"name" => "Stack Overflow", 
		"icon" => "stack-overflow", 
		"code" => "f16c", 
	],
	[
		"name" => "Star", 
		"icon" => "star", 
		"code" => "f005", 
	],
	[
		"name" => "Star Half", 
		"icon" => "star-half", 
		"code" => "f089", 
	],
	[
		"name" => "Staylinked", 
		"icon" => "staylinked", 
		"code" => "f3f5", 
	],
	[
		"name" => "Steam", 
		"icon" => "steam", 
		"code" => "f1b6", 
	],
	[
		"name" => "Steam Square", 
		"icon" => "steam-square", 
		"code" => "f1b7", 
	],
	[
		"name" => "Steam Symbol", 
		"icon" => "steam-symbol", 
		"code" => "f3f6", 
	],
	[
		"name" => "Step Backward", 
		"icon" => "step-backward", 
		"code" => "f048", 
	],
	[
		"name" => "Step Forward", 
		"icon" => "step-forward", 
		"code" => "f051", 
	],
	[
		"name" => "Stethoscope", 
		"icon" => "stethoscope", 
		"code" => "f0f1", 
	],
	[
		"name" => "Sticker Mule", 
		"icon" => "sticker-mule", 
		"code" => "f3f7", 
	],
	[
		"name" => "Sticky Note", 
		"icon" => "sticky-note", 
		"code" => "f249", 
	],
	[
		"name" => "Stop", 
		"icon" => "stop", 
		"code" => "f04d", 
	],
	[
		"name" => "Stop Circle", 
		"icon" => "stop-circle", 
		"code" => "f28d", 
	],
	[
		"name" => "Stopwatch", 
		"icon" => "stopwatch", 
		"code" => "f2f2", 
	],
	[
		"name" => "Strava", 
		"icon" => "strava", 
		"code" => "f428", 
	],
	[
		"name" => "Street View", 
		"icon" => "street-view", 
		"code" => "f21d", 
	],
	[
		"name" => "Strikethrough", 
		"icon" => "strikethrough", 
		"code" => "f0cc", 
	],
	[
		"name" => "Stripe", 
		"icon" => "stripe", 
		"code" => "f429", 
	],
	[
		"name" => "Stripe S", 
		"icon" => "stripe-s", 
		"code" => "f42a", 
	],
	[
		"name" => "Studiovinari", 
		"icon" => "studiovinari", 
		"code" => "f3f8", 
	],
	[
		"name" => "Stumbleupon", 
		"icon" => "stumbleupon", 
		"code" => "f1a4", 
	],
	[
		"name" => "Stumbleupon Circle", 
		"icon" => "stumbleupon-circle", 
		"code" => "f1a3", 
	],
	[
		"name" => "Subscript", 
		"icon" => "subscript", 
		"code" => "f12c", 
	],
	[
		"name" => "Subway", 
		"icon" => "subway", 
		"code" => "f239", 
	],
	[
		"name" => "Suitcase", 
		"icon" => "suitcase", 
		"code" => "f0f2", 
	],
	[
		"name" => "Sun", 
		"icon" => "sun", 
		"code" => "f185", 
	],
	[
		"name" => "Superpowers", 
		"icon" => "superpowers", 
		"code" => "f2dd", 
	],
	[
		"name" => "Superscript", 
		"icon" => "superscript", 
		"code" => "f12b", 
	],
	[
		"name" => "Supple", 
		"icon" => "supple", 
		"code" => "f3f9", 
	],
	[
		"name" => "Sync", 
		"icon" => "sync", 
		"code" => "f021", 
	],
	[
		"name" => "Sync Alt", 
		"icon" => "sync-alt", 
		"code" => "f2f1", 
	],
	[
		"name" => "Syringe", 
		"icon" => "syringe", 
		"code" => "f48e", 
	],
	[
		"name" => "Table", 
		"icon" => "table", 
		"code" => "f0ce", 
	],
	[
		"name" => "Table Tennis", 
		"icon" => "table-tennis", 
		"code" => "f45d", 
	],
	[
		"name" => "Tablet", 
		"icon" => "tablet", 
		"code" => "f10a", 
	],
	[
		"name" => "Tablet Alt", 
		"icon" => "tablet-alt", 
		"code" => "f3fa", 
	],
	[
		"name" => "Tachometer Alt", 
		"icon" => "tachometer-alt", 
		"code" => "f3fd", 
	],
	[
		"name" => "Tag", 
		"icon" => "tag", 
		"code" => "f02b", 
	],
	[
		"name" => "Tags", 
		"icon" => "tags", 
		"code" => "f02c", 
	],
	[
		"name" => "Tasks", 
		"icon" => "tasks", 
		"code" => "f0ae", 
	],
	[
		"name" => "Taxi", 
		"icon" => "taxi", 
		"code" => "f1ba", 
	],
	[
		"name" => "Telegram", 
		"icon" => "telegram", 
		"code" => "f2c6", 
	],
	[
		"name" => "Telegram Plane", 
		"icon" => "telegram-plane", 
		"code" => "f3fe", 
	],
	[
		"name" => "Tencent Weibo", 
		"icon" => "tencent-weibo", 
		"code" => "f1d5", 
	],
	[
		"name" => "Terminal", 
		"icon" => "terminal", 
		"code" => "f120", 
	],
	[
		"name" => "Text Height", 
		"icon" => "text-height", 
		"code" => "f034", 
	],
	[
		"name" => "Text Width", 
		"icon" => "text-width", 
		"code" => "f035", 
	],
	[
		"name" => "Th", 
		"icon" => "th", 
		"code" => "f00a", 
	],
	[
		"name" => "Th Large", 
		"icon" => "th-large", 
		"code" => "f009", 
	],
	[
		"name" => "Th List", 
		"icon" => "th-list", 
		"code" => "f00b", 
	],
	[
		"name" => "Themeisle", 
		"icon" => "themeisle", 
		"code" => "f2b2", 
	],
	[
		"name" => "Thermometer", 
		"icon" => "thermometer", 
		"code" => "f491", 
	],
	[
		"name" => "Thermometer Empty", 
		"icon" => "thermometer-empty", 
		"code" => "f2cb", 
	],
	[
		"name" => "Thermometer Full", 
		"icon" => "thermometer-full", 
		"code" => "f2c7", 
	],
	[
		"name" => "Thermometer Half", 
		"icon" => "thermometer-half", 
		"code" => "f2c9", 
	],
	[
		"name" => "Thermometer Quarter", 
		"icon" => "thermometer-quarter", 
		"code" => "f2ca", 
	],
	[
		"name" => "Thermometer Three Quarters", 
		"icon" => "thermometer-three-quarters", 
		"code" => "f2c8", 
	],
	[
		"name" => "Thumbs Down", 
		"icon" => "thumbs-down", 
		"code" => "f165", 
	],
	[
		"name" => "Thumbs Up", 
		"icon" => "thumbs-up", 
		"code" => "f164", 
	],
	[
		"name" => "Thumbtack", 
		"icon" => "thumbtack", 
		"code" => "f08d", 
	],
	[
		"name" => "Ticket Alt", 
		"icon" => "ticket-alt", 
		"code" => "f3ff", 
	],
	[
		"name" => "Times", 
		"icon" => "times", 
		"code" => "f00d", 
	],
	[
		"name" => "Times Circle", 
		"icon" => "times-circle", 
		"code" => "f057", 
	],
	[
		"name" => "Tint", 
		"icon" => "tint", 
		"code" => "f043", 
	],
	[
		"name" => "Toggle Off", 
		"icon" => "toggle-off", 
		"code" => "f204", 
	],
	[
		"name" => "Toggle On", 
		"icon" => "toggle-on", 
		"code" => "f205", 
	],
	[
		"name" => "Trademark", 
		"icon" => "trademark", 
		"code" => "f25c", 
	],
	[
		"name" => "Train", 
		"icon" => "train", 
		"code" => "f238", 
	],
	[
		"name" => "Transgender", 
		"icon" => "transgender", 
		"code" => "f224", 
	],
	[
		"name" => "Transgender Alt", 
		"icon" => "transgender-alt", 
		"code" => "f225", 
	],
	[
		"name" => "Trash", 
		"icon" => "trash", 
		"code" => "f1f8", 
	],
	[
		"name" => "Trash Alt", 
		"icon" => "trash-alt", 
		"code" => "f2ed", 
	],
	[
		"name" => "Tree", 
		"icon" => "tree", 
		"code" => "f1bb", 
	],
	[
		"name" => "Trello", 
		"icon" => "trello", 
		"code" => "f181", 
	],
	[
		"name" => "Tripadvisor", 
		"icon" => "tripadvisor", 
		"code" => "f262", 
	],
	[
		"name" => "Trophy", 
		"icon" => "trophy", 
		"code" => "f091", 
	],
	[
		"name" => "Truck", 
		"icon" => "truck", 
		"code" => "f0d1", 
	],
	[
		"name" => "Tty", 
		"icon" => "tty", 
		"code" => "f1e4", 
	],
	[
		"name" => "Tumblr", 
		"icon" => "tumblr", 
		"code" => "f173", 
	],
	[
		"name" => "Tumblr Square", 
		"icon" => "tumblr-square", 
		"code" => "f174", 
	],
	[
		"name" => "Tv", 
		"icon" => "tv", 
		"code" => "f26c", 
	],
	[
		"name" => "Twitch", 
		"icon" => "twitch", 
		"code" => "f1e8", 
	],
	[
		"name" => "Twitter", 
		"icon" => "twitter", 
		"code" => "f099", 
	],
	[
		"name" => "Twitter Square", 
		"icon" => "twitter-square", 
		"code" => "f081", 
	],
	[
		"name" => "Typo3", 
		"icon" => "typo3", 
		"code" => "f42b", 
	],
	[
		"name" => "Uber", 
		"icon" => "uber", 
		"code" => "f402", 
	],
	[
		"name" => "Uikit", 
		"icon" => "uikit", 
		"code" => "f403", 
	],
	[
		"name" => "Umbrella", 
		"icon" => "umbrella", 
		"code" => "f0e9", 
	],
	[
		"name" => "Underline", 
		"icon" => "underline", 
		"code" => "f0cd", 
	],
	[
		"name" => "Undo", 
		"icon" => "undo", 
		"code" => "f0e2", 
	],
	[
		"name" => "Undo Alt", 
		"icon" => "undo-alt", 
		"code" => "f2ea", 
	],
	[
		"name" => "Uniregistry", 
		"icon" => "uniregistry", 
		"code" => "f404", 
	],
	[
		"name" => "Universal Access", 
		"icon" => "universal-access", 
		"code" => "f29a", 
	],
	[
		"name" => "University", 
		"icon" => "university", 
		"code" => "f19c", 
	],
	[
		"name" => "Unlink", 
		"icon" => "unlink", 
		"code" => "f127", 
	],
	[
		"name" => "Unlock", 
		"icon" => "unlock", 
		"code" => "f09c", 
	],
	[
		"name" => "Unlock Alt", 
		"icon" => "unlock-alt", 
		"code" => "f13e", 
	],
	[
		"name" => "Untappd", 
		"icon" => "untappd", 
		"code" => "f405", 
	],
	[
		"name" => "Upload", 
		"icon" => "upload", 
		"code" => "f093", 
	],
	[
		"name" => "Usb", 
		"icon" => "usb", 
		"code" => "f287", 
	],
	[
		"name" => "User", 
		"icon" => "user", 
		"code" => "f007", 
	],
	[
		"name" => "User Circle", 
		"icon" => "user-circle", 
		"code" => "f2bd", 
	],
	[
		"name" => "User Md", 
		"icon" => "user-md", 
		"code" => "f0f0", 
	],
	[
		"name" => "User Plus", 
		"icon" => "user-plus", 
		"code" => "f234", 
	],
	[
		"name" => "User Secret", 
		"icon" => "user-secret", 
		"code" => "f21b", 
	],
	[
		"name" => "User Times", 
		"icon" => "user-times", 
		"code" => "f235", 
	],
	[
		"name" => "Users", 
		"icon" => "users", 
		"code" => "f0c0", 
	],
	[
		"name" => "Ussunnah", 
		"icon" => "ussunnah", 
		"code" => "f407", 
	],
	[
		"name" => "Utensil Spoon", 
		"icon" => "utensil-spoon", 
		"code" => "f2e5", 
	],
	[
		"name" => "Utensils", 
		"icon" => "utensils", 
		"code" => "f2e7", 
	],
	[
		"name" => "Vaadin", 
		"icon" => "vaadin", 
		"code" => "f408", 
	],
	[
		"name" => "Venus", 
		"icon" => "venus", 
		"code" => "f221", 
	],
	[
		"name" => "Venus Double", 
		"icon" => "venus-double", 
		"code" => "f226", 
	],
	[
		"name" => "Venus Mars", 
		"icon" => "venus-mars", 
		"code" => "f228", 
	],
	[
		"name" => "Viacoin", 
		"icon" => "viacoin", 
		"code" => "f237", 
	],
	[
		"name" => "Viadeo", 
		"icon" => "viadeo", 
		"code" => "f2a9", 
	],
	[
		"name" => "Viadeo Square", 
		"icon" => "viadeo-square", 
		"code" => "f2aa", 
	],
	[
		"name" => "Viber", 
		"icon" => "viber", 
		"code" => "f409", 
	],
	[
		"name" => "Video", 
		"icon" => "video", 
		"code" => "f03d", 
	],
	[
		"name" => "Vimeo", 
		"icon" => "vimeo", 
		"code" => "f40a", 
	],
	[
		"name" => "Vimeo Square", 
		"icon" => "vimeo-square", 
		"code" => "f194", 
	],
	[
		"name" => "Vimeo V", 
		"icon" => "vimeo-v", 
		"code" => "f27d", 
	],
	[
		"name" => "Vine", 
		"icon" => "vine", 
		"code" => "f1ca", 
	],
	[
		"name" => "Vk", 
		"icon" => "vk", 
		"code" => "f189", 
	],
	[
		"name" => "Vnv", 
		"icon" => "vnv", 
		"code" => "f40b", 
	],
	[
		"name" => "Volleyball Ball", 
		"icon" => "volleyball-ball", 
		"code" => "f45f", 
	],
	[
		"name" => "Volume Down", 
		"icon" => "volume-down", 
		"code" => "f027", 
	],
	[
		"name" => "Volume Off", 
		"icon" => "volume-off", 
		"code" => "f026", 
	],
	[
		"name" => "Volume Up", 
		"icon" => "volume-up", 
		"code" => "f028", 
	],
	[
		"name" => "Vuejs", 
		"icon" => "vuejs", 
		"code" => "f41f", 
	],
	[
		"name" => "Warehouse", 
		"icon" => "warehouse", 
		"code" => "f494", 
	],
	[
		"name" => "Weibo", 
		"icon" => "weibo", 
		"code" => "f18a", 
	],
	[
		"name" => "Weight", 
		"icon" => "weight", 
		"code" => "f496", 
	],
	[
		"name" => "Weixin", 
		"icon" => "weixin", 
		"code" => "f1d7", 
	],
	[
		"name" => "Whatsapp", 
		"icon" => "whatsapp", 
		"code" => "f232", 
	],
	[
		"name" => "Whatsapp Square", 
		"icon" => "whatsapp-square", 
		"code" => "f40c", 
	],
	[
		"name" => "Wheelchair", 
		"icon" => "wheelchair", 
		"code" => "f193", 
	],
	[
		"name" => "Whmcs", 
		"icon" => "whmcs", 
		"code" => "f40d", 
	],
	[
		"name" => "Wifi", 
		"icon" => "wifi", 
		"code" => "f1eb", 
	],
	[
		"name" => "Wikipedia W", 
		"icon" => "wikipedia-w", 
		"code" => "f266", 
	],
	[
		"name" => "Window Close", 
		"icon" => "window-close", 
		"code" => "f410", 
	],
	[
		"name" => "Window Maximize", 
		"icon" => "window-maximize", 
		"code" => "f2d0", 
	],
	[
		"name" => "Window Minimize", 
		"icon" => "window-minimize", 
		"code" => "f2d1", 
	],
	[
		"name" => "Window Restore", 
		"icon" => "window-restore", 
		"code" => "f2d2", 
	],
	[
		"name" => "Windows", 
		"icon" => "windows", 
		"code" => "f17a", 
	],
	[
		"name" => "Won Sign", 
		"icon" => "won-sign", 
		"code" => "f159", 
	],
	[
		"name" => "Wordpress", 
		"icon" => "wordpress", 
		"code" => "f19a", 
	],
	[
		"name" => "Wordpress Simple", 
		"icon" => "wordpress-simple", 
		"code" => "f411", 
	],
	[
		"name" => "Wpbeginner", 
		"icon" => "wpbeginner", 
		"code" => "f297", 
	],
	[
		"name" => "Wpexplorer", 
		"icon" => "wpexplorer", 
		"code" => "f2de", 
	],
	[
		"name" => "Wpforms", 
		"icon" => "wpforms", 
		"code" => "f298", 
	],
	[
		"name" => "Wrench", 
		"icon" => "wrench", 
		"code" => "f0ad", 
	],
	[
		"name" => "Xbox", 
		"icon" => "xbox", 
		"code" => "f412", 
	],
	[
		"name" => "Xing", 
		"icon" => "xing", 
		"code" => "f168", 
	],
	[
		"name" => "Xing Square", 
		"icon" => "xing-square", 
		"code" => "f169", 
	],
	[
		"name" => "Y Combinator", 
		"icon" => "y-combinator", 
		"code" => "f23b", 
	],
	[
		"name" => "Yahoo", 
		"icon" => "yahoo", 
		"code" => "f19e", 
	],
	[
		"name" => "Yandex", 
		"icon" => "yandex", 
		"code" => "f413", 
	],
	[
		"name" => "Yandex International", 
		"icon" => "yandex-international", 
		"code" => "f414", 
	],
	[
		"name" => "Yelp", 
		"icon" => "yelp", 
		"code" => "f1e9", 
	],
	[
		"name" => "Yen Sign", 
		"icon" => "yen-sign", 
		"code" => "f157", 
	],
	[
		"name" => "Yoast", 
		"icon" => "yoast", 
		"code" => "f2b1", 
	],
	[
		"name" => "Youtube", 
		"icon" => "youtube", 
		"code" => "f167", 
	],
	[
		"name" => "Youtube Square", 
		"icon" => "youtube-square", 
		"code" => "f431", 
	],
];
