<?php

	/**
	 * FontAwesome Icon List for version 4.7.0
	 * This is a format best suited for general use in PHP
	 * @author: Theo Komninos
	 * @version: 0.0.1
	 * @todo: Names might need a bit of polishing, since they've been autogenerated.
	 */

	const FONT_AWESOME = [
	[
		"name" => "500px", 
		"icon" => "500px", 
		"code" => "f26e", 
	],
	[
		"name" => "Address Book", 
		"icon" => "address-book", 
		"code" => "f2b9", 
	],
	[
		"name" => "Address Book O", 
		"icon" => "address-book-o", 
		"code" => "f2ba", 
	],
	[
		"name" => "Address Card", 
		"icon" => "address-card", 
		"code" => "f2bb", 
	],
	[
		"name" => "Address Card O", 
		"icon" => "address-card-o", 
		"code" => "f2bc", 
	],
	[
		"name" => "Adjust", 
		"icon" => "adjust", 
		"code" => "f042", 
	],
	[
		"name" => "Adn", 
		"icon" => "adn", 
		"code" => "f170", 
	],
	[
		"name" => "Align Center", 
		"icon" => "align-center", 
		"code" => "f037", 
	],
	[
		"name" => "Align Justify", 
		"icon" => "align-justify", 
		"code" => "f039", 
	],
	[
		"name" => "Align Left", 
		"icon" => "align-left", 
		"code" => "f036", 
	],
	[
		"name" => "Align Right", 
		"icon" => "align-right", 
		"code" => "f038", 
	],
	[
		"name" => "Amazon", 
		"icon" => "amazon", 
		"code" => "f270", 
	],
	[
		"name" => "Ambulance", 
		"icon" => "ambulance", 
		"code" => "f0f9", 
	],
	[
		"name" => "American Sign Language Interpreting", 
		"icon" => "american-sign-language-interpreting", 
		"code" => "f2a3", 
	],
	[
		"name" => "Anchor", 
		"icon" => "anchor", 
		"code" => "f13d", 
	],
	[
		"name" => "Android", 
		"icon" => "android", 
		"code" => "f17b", 
	],
	[
		"name" => "Angellist", 
		"icon" => "angellist", 
		"code" => "f209", 
	],
	[
		"name" => "Angle Double Down", 
		"icon" => "angle-double-down", 
		"code" => "f103", 
	],
	[
		"name" => "Angle Double Left", 
		"icon" => "angle-double-left", 
		"code" => "f100", 
	],
	[
		"name" => "Angle Double Right", 
		"icon" => "angle-double-right", 
		"code" => "f101", 
	],
	[
		"name" => "Angle Double Up", 
		"icon" => "angle-double-up", 
		"code" => "f102", 
	],
	[
		"name" => "Angle Down", 
		"icon" => "angle-down", 
		"code" => "f107", 
	],
	[
		"name" => "Angle Left", 
		"icon" => "angle-left", 
		"code" => "f104", 
	],
	[
		"name" => "Angle Right", 
		"icon" => "angle-right", 
		"code" => "f105", 
	],
	[
		"name" => "Angle Up", 
		"icon" => "angle-up", 
		"code" => "f106", 
	],
	[
		"name" => "Apple", 
		"icon" => "apple", 
		"code" => "f179", 
	],
	[
		"name" => "Archive", 
		"icon" => "archive", 
		"code" => "f187", 
	],
	[
		"name" => "Area Chart", 
		"icon" => "area-chart", 
		"code" => "f1fe", 
	],
	[
		"name" => "Arrow Circle Down", 
		"icon" => "arrow-circle-down", 
		"code" => "f0ab", 
	],
	[
		"name" => "Arrow Circle Left", 
		"icon" => "arrow-circle-left", 
		"code" => "f0a8", 
	],
	[
		"name" => "Arrow Circle O Down", 
		"icon" => "arrow-circle-o-down", 
		"code" => "f01a", 
	],
	[
		"name" => "Arrow Circle O Left", 
		"icon" => "arrow-circle-o-left", 
		"code" => "f190", 
	],
	[
		"name" => "Arrow Circle O Right", 
		"icon" => "arrow-circle-o-right", 
		"code" => "f18e", 
	],
	[
		"name" => "Arrow Circle O Up", 
		"icon" => "arrow-circle-o-up", 
		"code" => "f01b", 
	],
	[
		"name" => "Arrow Circle Right", 
		"icon" => "arrow-circle-right", 
		"code" => "f0a9", 
	],
	[
		"name" => "Arrow Circle Up", 
		"icon" => "arrow-circle-up", 
		"code" => "f0aa", 
	],
	[
		"name" => "Arrow Down", 
		"icon" => "arrow-down", 
		"code" => "f063", 
	],
	[
		"name" => "Arrow Left", 
		"icon" => "arrow-left", 
		"code" => "f060", 
	],
	[
		"name" => "Arrow Right", 
		"icon" => "arrow-right", 
		"code" => "f061", 
	],
	[
		"name" => "Arrow Up", 
		"icon" => "arrow-up", 
		"code" => "f062", 
	],
	[
		"name" => "Arrows", 
		"icon" => "arrows", 
		"code" => "f047", 
	],
	[
		"name" => "Arrows Alt", 
		"icon" => "arrows-alt", 
		"code" => "f0b2", 
	],
	[
		"name" => "Arrows H", 
		"icon" => "arrows-h", 
		"code" => "f07e", 
	],
	[
		"name" => "Arrows V", 
		"icon" => "arrows-v", 
		"code" => "f07d", 
	],
	[
		"name" => "Assistive Listening Systems", 
		"icon" => "assistive-listening-systems", 
		"code" => "f2a2", 
	],
	[
		"name" => "Asterisk", 
		"icon" => "asterisk", 
		"code" => "f069", 
	],
	[
		"name" => "At", 
		"icon" => "at", 
		"code" => "f1fa", 
	],
	[
		"name" => "Audio Description", 
		"icon" => "audio-description", 
		"code" => "f29e", 
	],
	[
		"name" => "Backward", 
		"icon" => "backward", 
		"code" => "f04a", 
	],
	[
		"name" => "Balance Scale", 
		"icon" => "balance-scale", 
		"code" => "f24e", 
	],
	[
		"name" => "Ban", 
		"icon" => "ban", 
		"code" => "f05e", 
	],
	[
		"name" => "Bandcamp", 
		"icon" => "bandcamp", 
		"code" => "f2d5", 
	],
	[
		"name" => "Bar Chart", 
		"icon" => "bar-chart", 
		"code" => "f080", 
	],
	[
		"name" => "Barcode", 
		"icon" => "barcode", 
		"code" => "f02a", 
	],
	[
		"name" => "Bars", 
		"icon" => "bars", 
		"code" => "f0c9", 
	],
	[
		"name" => "Bath", 
		"icon" => "bath", 
		"code" => "f2cd", 
	],
	[
		"name" => "Battery Empty", 
		"icon" => "battery-empty", 
		"code" => "f244", 
	],
	[
		"name" => "Battery Full", 
		"icon" => "battery-full", 
		"code" => "f240", 
	],
	[
		"name" => "Battery Half", 
		"icon" => "battery-half", 
		"code" => "f242", 
	],
	[
		"name" => "Battery Quarter", 
		"icon" => "battery-quarter", 
		"code" => "f243", 
	],
	[
		"name" => "Battery Three Quarters", 
		"icon" => "battery-three-quarters", 
		"code" => "f241", 
	],
	[
		"name" => "Bed", 
		"icon" => "bed", 
		"code" => "f236", 
	],
	[
		"name" => "Beer", 
		"icon" => "beer", 
		"code" => "f0fc", 
	],
	[
		"name" => "Behance", 
		"icon" => "behance", 
		"code" => "f1b4", 
	],
	[
		"name" => "Behance Square", 
		"icon" => "behance-square", 
		"code" => "f1b5", 
	],
	[
		"name" => "Bell", 
		"icon" => "bell", 
		"code" => "f0f3", 
	],
	[
		"name" => "Bell O", 
		"icon" => "bell-o", 
		"code" => "f0a2", 
	],
	[
		"name" => "Bell Slash", 
		"icon" => "bell-slash", 
		"code" => "f1f6", 
	],
	[
		"name" => "Bell Slash O", 
		"icon" => "bell-slash-o", 
		"code" => "f1f7", 
	],
	[
		"name" => "Bicycle", 
		"icon" => "bicycle", 
		"code" => "f206", 
	],
	[
		"name" => "Binoculars", 
		"icon" => "binoculars", 
		"code" => "f1e5", 
	],
	[
		"name" => "Birthday Cake", 
		"icon" => "birthday-cake", 
		"code" => "f1fd", 
	],
	[
		"name" => "Bitbucket", 
		"icon" => "bitbucket", 
		"code" => "f171", 
	],
	[
		"name" => "Bitbucket Square", 
		"icon" => "bitbucket-square", 
		"code" => "f172", 
	],
	[
		"name" => "Black Tie", 
		"icon" => "black-tie", 
		"code" => "f27e", 
	],
	[
		"name" => "Blind", 
		"icon" => "blind", 
		"code" => "f29d", 
	],
	[
		"name" => "Bluetooth", 
		"icon" => "bluetooth", 
		"code" => "f293", 
	],
	[
		"name" => "Bluetooth B", 
		"icon" => "bluetooth-b", 
		"code" => "f294", 
	],
	[
		"name" => "Bold", 
		"icon" => "bold", 
		"code" => "f032", 
	],
	[
		"name" => "Bolt", 
		"icon" => "bolt", 
		"code" => "f0e7", 
	],
	[
		"name" => "Bomb", 
		"icon" => "bomb", 
		"code" => "f1e2", 
	],
	[
		"name" => "Book", 
		"icon" => "book", 
		"code" => "f02d", 
	],
	[
		"name" => "Bookmark", 
		"icon" => "bookmark", 
		"code" => "f02e", 
	],
	[
		"name" => "Bookmark O", 
		"icon" => "bookmark-o", 
		"code" => "f097", 
	],
	[
		"name" => "Braille", 
		"icon" => "braille", 
		"code" => "f2a1", 
	],
	[
		"name" => "Briefcase", 
		"icon" => "briefcase", 
		"code" => "f0b1", 
	],
	[
		"name" => "Btc", 
		"icon" => "btc", 
		"code" => "f15a", 
	],
	[
		"name" => "Bug", 
		"icon" => "bug", 
		"code" => "f188", 
	],
	[
		"name" => "Building", 
		"icon" => "building", 
		"code" => "f1ad", 
	],
	[
		"name" => "Building O", 
		"icon" => "building-o", 
		"code" => "f0f7", 
	],
	[
		"name" => "Bullhorn", 
		"icon" => "bullhorn", 
		"code" => "f0a1", 
	],
	[
		"name" => "Bullseye", 
		"icon" => "bullseye", 
		"code" => "f140", 
	],
	[
		"name" => "Bus", 
		"icon" => "bus", 
		"code" => "f207", 
	],
	[
		"name" => "Buysellads", 
		"icon" => "buysellads", 
		"code" => "f20d", 
	],
	[
		"name" => "Calculator", 
		"icon" => "calculator", 
		"code" => "f1ec", 
	],
	[
		"name" => "Calendar", 
		"icon" => "calendar", 
		"code" => "f073", 
	],
	[
		"name" => "Calendar Check O", 
		"icon" => "calendar-check-o", 
		"code" => "f274", 
	],
	[
		"name" => "Calendar Minus O", 
		"icon" => "calendar-minus-o", 
		"code" => "f272", 
	],
	[
		"name" => "Calendar O", 
		"icon" => "calendar-o", 
		"code" => "f133", 
	],
	[
		"name" => "Calendar Plus O", 
		"icon" => "calendar-plus-o", 
		"code" => "f271", 
	],
	[
		"name" => "Calendar Times O", 
		"icon" => "calendar-times-o", 
		"code" => "f273", 
	],
	[
		"name" => "Camera", 
		"icon" => "camera", 
		"code" => "f030", 
	],
	[
		"name" => "Camera Retro", 
		"icon" => "camera-retro", 
		"code" => "f083", 
	],
	[
		"name" => "Car", 
		"icon" => "car", 
		"code" => "f1b9", 
	],
	[
		"name" => "Caret Down", 
		"icon" => "caret-down", 
		"code" => "f0d7", 
	],
	[
		"name" => "Caret Left", 
		"icon" => "caret-left", 
		"code" => "f0d9", 
	],
	[
		"name" => "Caret Right", 
		"icon" => "caret-right", 
		"code" => "f0da", 
	],
	[
		"name" => "Caret Square O Down", 
		"icon" => "caret-square-o-down", 
		"code" => "f150", 
	],
	[
		"name" => "Caret Square O Left", 
		"icon" => "caret-square-o-left", 
		"code" => "f191", 
	],
	[
		"name" => "Caret Square O Right", 
		"icon" => "caret-square-o-right", 
		"code" => "f152", 
	],
	[
		"name" => "Caret Square O Up", 
		"icon" => "caret-square-o-up", 
		"code" => "f151", 
	],
	[
		"name" => "Caret Up", 
		"icon" => "caret-up", 
		"code" => "f0d8", 
	],
	[
		"name" => "Cart Arrow Down", 
		"icon" => "cart-arrow-down", 
		"code" => "f218", 
	],
	[
		"name" => "Cart Plus", 
		"icon" => "cart-plus", 
		"code" => "f217", 
	],
	[
		"name" => "Cc", 
		"icon" => "cc", 
		"code" => "f20a", 
	],
	[
		"name" => "Cc Amex", 
		"icon" => "cc-amex", 
		"code" => "f1f3", 
	],
	[
		"name" => "Cc Diners Club", 
		"icon" => "cc-diners-club", 
		"code" => "f24c", 
	],
	[
		"name" => "Cc Discover", 
		"icon" => "cc-discover", 
		"code" => "f1f2", 
	],
	[
		"name" => "Cc Jcb", 
		"icon" => "cc-jcb", 
		"code" => "f24b", 
	],
	[
		"name" => "Cc Mastercard", 
		"icon" => "cc-mastercard", 
		"code" => "f1f1", 
	],
	[
		"name" => "Cc Paypal", 
		"icon" => "cc-paypal", 
		"code" => "f1f4", 
	],
	[
		"name" => "Cc Stripe", 
		"icon" => "cc-stripe", 
		"code" => "f1f5", 
	],
	[
		"name" => "Cc Visa", 
		"icon" => "cc-visa", 
		"code" => "f1f0", 
	],
	[
		"name" => "Certificate", 
		"icon" => "certificate", 
		"code" => "f0a3", 
	],
	[
		"name" => "Chain Broken", 
		"icon" => "chain-broken", 
		"code" => "f127", 
	],
	[
		"name" => "Check", 
		"icon" => "check", 
		"code" => "f00c", 
	],
	[
		"name" => "Check Circle", 
		"icon" => "check-circle", 
		"code" => "f058", 
	],
	[
		"name" => "Check Circle O", 
		"icon" => "check-circle-o", 
		"code" => "f05d", 
	],
	[
		"name" => "Check Square", 
		"icon" => "check-square", 
		"code" => "f14a", 
	],
	[
		"name" => "Check Square O", 
		"icon" => "check-square-o", 
		"code" => "f046", 
	],
	[
		"name" => "Chevron Circle Down", 
		"icon" => "chevron-circle-down", 
		"code" => "f13a", 
	],
	[
		"name" => "Chevron Circle Left", 
		"icon" => "chevron-circle-left", 
		"code" => "f137", 
	],
	[
		"name" => "Chevron Circle Right", 
		"icon" => "chevron-circle-right", 
		"code" => "f138", 
	],
	[
		"name" => "Chevron Circle Up", 
		"icon" => "chevron-circle-up", 
		"code" => "f139", 
	],
	[
		"name" => "Chevron Down", 
		"icon" => "chevron-down", 
		"code" => "f078", 
	],
	[
		"name" => "Chevron Left", 
		"icon" => "chevron-left", 
		"code" => "f053", 
	],
	[
		"name" => "Chevron Right", 
		"icon" => "chevron-right", 
		"code" => "f054", 
	],
	[
		"name" => "Chevron Up", 
		"icon" => "chevron-up", 
		"code" => "f077", 
	],
	[
		"name" => "Child", 
		"icon" => "child", 
		"code" => "f1ae", 
	],
	[
		"name" => "Chrome", 
		"icon" => "chrome", 
		"code" => "f268", 
	],
	[
		"name" => "Circle", 
		"icon" => "circle", 
		"code" => "f111", 
	],
	[
		"name" => "Circle O", 
		"icon" => "circle-o", 
		"code" => "f10c", 
	],
	[
		"name" => "Circle O Notch", 
		"icon" => "circle-o-notch", 
		"code" => "f1ce", 
	],
	[
		"name" => "Circle Thin", 
		"icon" => "circle-thin", 
		"code" => "f1db", 
	],
	[
		"name" => "Clipboard", 
		"icon" => "clipboard", 
		"code" => "f0ea", 
	],
	[
		"name" => "Clock O", 
		"icon" => "clock-o", 
		"code" => "f017", 
	],
	[
		"name" => "Clone", 
		"icon" => "clone", 
		"code" => "f24d", 
	],
	[
		"name" => "Cloud", 
		"icon" => "cloud", 
		"code" => "f0c2", 
	],
	[
		"name" => "Cloud Download", 
		"icon" => "cloud-download", 
		"code" => "f0ed", 
	],
	[
		"name" => "Cloud Upload", 
		"icon" => "cloud-upload", 
		"code" => "f0ee", 
	],
	[
		"name" => "Code", 
		"icon" => "code", 
		"code" => "f121", 
	],
	[
		"name" => "Code Fork", 
		"icon" => "code-fork", 
		"code" => "f126", 
	],
	[
		"name" => "Codepen", 
		"icon" => "codepen", 
		"code" => "f1cb", 
	],
	[
		"name" => "Codiepie", 
		"icon" => "codiepie", 
		"code" => "f284", 
	],
	[
		"name" => "Coffee", 
		"icon" => "coffee", 
		"code" => "f0f4", 
	],
	[
		"name" => "Cog", 
		"icon" => "cog", 
		"code" => "f013", 
	],
	[
		"name" => "Cogs", 
		"icon" => "cogs", 
		"code" => "f085", 
	],
	[
		"name" => "Columns", 
		"icon" => "columns", 
		"code" => "f0db", 
	],
	[
		"name" => "Comment", 
		"icon" => "comment", 
		"code" => "f075", 
	],
	[
		"name" => "Comment O", 
		"icon" => "comment-o", 
		"code" => "f0e5", 
	],
	[
		"name" => "Commenting", 
		"icon" => "commenting", 
		"code" => "f27a", 
	],
	[
		"name" => "Commenting O", 
		"icon" => "commenting-o", 
		"code" => "f27b", 
	],
	[
		"name" => "Comments", 
		"icon" => "comments", 
		"code" => "f086", 
	],
	[
		"name" => "Comments O", 
		"icon" => "comments-o", 
		"code" => "f0e6", 
	],
	[
		"name" => "Compass", 
		"icon" => "compass", 
		"code" => "f14e", 
	],
	[
		"name" => "Compress", 
		"icon" => "compress", 
		"code" => "f066", 
	],
	[
		"name" => "Connectdevelop", 
		"icon" => "connectdevelop", 
		"code" => "f20e", 
	],
	[
		"name" => "Contao", 
		"icon" => "contao", 
		"code" => "f26d", 
	],
	[
		"name" => "Copyright", 
		"icon" => "copyright", 
		"code" => "f1f9", 
	],
	[
		"name" => "Creative Commons", 
		"icon" => "creative-commons", 
		"code" => "f25e", 
	],
	[
		"name" => "Credit Card", 
		"icon" => "credit-card", 
		"code" => "f09d", 
	],
	[
		"name" => "Credit Card Alt", 
		"icon" => "credit-card-alt", 
		"code" => "f283", 
	],
	[
		"name" => "Crop", 
		"icon" => "crop", 
		"code" => "f125", 
	],
	[
		"name" => "Crosshairs", 
		"icon" => "crosshairs", 
		"code" => "f05b", 
	],
	[
		"name" => "Css3", 
		"icon" => "css3", 
		"code" => "f13c", 
	],
	[
		"name" => "Cube", 
		"icon" => "cube", 
		"code" => "f1b2", 
	],
	[
		"name" => "Cubes", 
		"icon" => "cubes", 
		"code" => "f1b3", 
	],
	[
		"name" => "Cutlery", 
		"icon" => "cutlery", 
		"code" => "f0f5", 
	],
	[
		"name" => "Dashcube", 
		"icon" => "dashcube", 
		"code" => "f210", 
	],
	[
		"name" => "Database", 
		"icon" => "database", 
		"code" => "f1c0", 
	],
	[
		"name" => "Deaf", 
		"icon" => "deaf", 
		"code" => "f2a4", 
	],
	[
		"name" => "Delicious", 
		"icon" => "delicious", 
		"code" => "f1a5", 
	],
	[
		"name" => "Desktop", 
		"icon" => "desktop", 
		"code" => "f108", 
	],
	[
		"name" => "Deviantart", 
		"icon" => "deviantart", 
		"code" => "f1bd", 
	],
	[
		"name" => "Diamond", 
		"icon" => "diamond", 
		"code" => "f219", 
	],
	[
		"name" => "Digg", 
		"icon" => "digg", 
		"code" => "f1a6", 
	],
	[
		"name" => "Dot Circle O", 
		"icon" => "dot-circle-o", 
		"code" => "f192", 
	],
	[
		"name" => "Download", 
		"icon" => "download", 
		"code" => "f019", 
	],
	[
		"name" => "Dribbble", 
		"icon" => "dribbble", 
		"code" => "f17d", 
	],
	[
		"name" => "Dropbox", 
		"icon" => "dropbox", 
		"code" => "f16b", 
	],
	[
		"name" => "Drupal", 
		"icon" => "drupal", 
		"code" => "f1a9", 
	],
	[
		"name" => "Edge", 
		"icon" => "edge", 
		"code" => "f282", 
	],
	[
		"name" => "Eercast", 
		"icon" => "eercast", 
		"code" => "f2da", 
	],
	[
		"name" => "Eject", 
		"icon" => "eject", 
		"code" => "f052", 
	],
	[
		"name" => "Ellipsis H", 
		"icon" => "ellipsis-h", 
		"code" => "f141", 
	],
	[
		"name" => "Ellipsis V", 
		"icon" => "ellipsis-v", 
		"code" => "f142", 
	],
	[
		"name" => "Empire", 
		"icon" => "empire", 
		"code" => "f1d1", 
	],
	[
		"name" => "Envelope", 
		"icon" => "envelope", 
		"code" => "f0e0", 
	],
	[
		"name" => "Envelope O", 
		"icon" => "envelope-o", 
		"code" => "f003", 
	],
	[
		"name" => "Envelope Open", 
		"icon" => "envelope-open", 
		"code" => "f2b6", 
	],
	[
		"name" => "Envelope Open O", 
		"icon" => "envelope-open-o", 
		"code" => "f2b7", 
	],
	[
		"name" => "Envelope Square", 
		"icon" => "envelope-square", 
		"code" => "f199", 
	],
	[
		"name" => "Envira", 
		"icon" => "envira", 
		"code" => "f299", 
	],
	[
		"name" => "Eraser", 
		"icon" => "eraser", 
		"code" => "f12d", 
	],
	[
		"name" => "Etsy", 
		"icon" => "etsy", 
		"code" => "f2d7", 
	],
	[
		"name" => "Eur", 
		"icon" => "eur", 
		"code" => "f153", 
	],
	[
		"name" => "Exchange", 
		"icon" => "exchange", 
		"code" => "f0ec", 
	],
	[
		"name" => "Exclamation", 
		"icon" => "exclamation", 
		"code" => "f12a", 
	],
	[
		"name" => "Exclamation Circle", 
		"icon" => "exclamation-circle", 
		"code" => "f06a", 
	],
	[
		"name" => "Exclamation Triangle", 
		"icon" => "exclamation-triangle", 
		"code" => "f071", 
	],
	[
		"name" => "Expand", 
		"icon" => "expand", 
		"code" => "f065", 
	],
	[
		"name" => "Expeditedssl", 
		"icon" => "expeditedssl", 
		"code" => "f23e", 
	],
	[
		"name" => "External Link", 
		"icon" => "external-link", 
		"code" => "f08e", 
	],
	[
		"name" => "External Link Square", 
		"icon" => "external-link-square", 
		"code" => "f14c", 
	],
	[
		"name" => "Eye", 
		"icon" => "eye", 
		"code" => "f06e", 
	],
	[
		"name" => "Eye Slash", 
		"icon" => "eye-slash", 
		"code" => "f070", 
	],
	[
		"name" => "Eyedropper", 
		"icon" => "eyedropper", 
		"code" => "f1fb", 
	],
	[
		"name" => "Facebook", 
		"icon" => "facebook", 
		"code" => "f09a", 
	],
	[
		"name" => "Facebook Official", 
		"icon" => "facebook-official", 
		"code" => "f230", 
	],
	[
		"name" => "Facebook Square", 
		"icon" => "facebook-square", 
		"code" => "f082", 
	],
	[
		"name" => "Fast Backward", 
		"icon" => "fast-backward", 
		"code" => "f049", 
	],
	[
		"name" => "Fast Forward", 
		"icon" => "fast-forward", 
		"code" => "f050", 
	],
	[
		"name" => "Fax", 
		"icon" => "fax", 
		"code" => "f1ac", 
	],
	[
		"name" => "Female", 
		"icon" => "female", 
		"code" => "f182", 
	],
	[
		"name" => "Fighter Jet", 
		"icon" => "fighter-jet", 
		"code" => "f0fb", 
	],
	[
		"name" => "File", 
		"icon" => "file", 
		"code" => "f15b", 
	],
	[
		"name" => "File Archive O", 
		"icon" => "file-archive-o", 
		"code" => "f1c6", 
	],
	[
		"name" => "File Audio O", 
		"icon" => "file-audio-o", 
		"code" => "f1c7", 
	],
	[
		"name" => "File Code O", 
		"icon" => "file-code-o", 
		"code" => "f1c9", 
	],
	[
		"name" => "File Excel O", 
		"icon" => "file-excel-o", 
		"code" => "f1c3", 
	],
	[
		"name" => "File Image O", 
		"icon" => "file-image-o", 
		"code" => "f1c5", 
	],
	[
		"name" => "File O", 
		"icon" => "file-o", 
		"code" => "f016", 
	],
	[
		"name" => "File Pdf O", 
		"icon" => "file-pdf-o", 
		"code" => "f1c1", 
	],
	[
		"name" => "File Powerpoint O", 
		"icon" => "file-powerpoint-o", 
		"code" => "f1c4", 
	],
	[
		"name" => "File Text", 
		"icon" => "file-text", 
		"code" => "f15c", 
	],
	[
		"name" => "File Text O", 
		"icon" => "file-text-o", 
		"code" => "f0f6", 
	],
	[
		"name" => "File Video O", 
		"icon" => "file-video-o", 
		"code" => "f1c8", 
	],
	[
		"name" => "File Word O", 
		"icon" => "file-word-o", 
		"code" => "f1c2", 
	],
	[
		"name" => "Files O", 
		"icon" => "files-o", 
		"code" => "f0c5", 
	],
	[
		"name" => "Film", 
		"icon" => "film", 
		"code" => "f008", 
	],
	[
		"name" => "Filter", 
		"icon" => "filter", 
		"code" => "f0b0", 
	],
	[
		"name" => "Fire", 
		"icon" => "fire", 
		"code" => "f06d", 
	],
	[
		"name" => "Fire Extinguisher", 
		"icon" => "fire-extinguisher", 
		"code" => "f134", 
	],
	[
		"name" => "Firefox", 
		"icon" => "firefox", 
		"code" => "f269", 
	],
	[
		"name" => "First Order", 
		"icon" => "first-order", 
		"code" => "f2b0", 
	],
	[
		"name" => "Flag", 
		"icon" => "flag", 
		"code" => "f024", 
	],
	[
		"name" => "Flag Checkered", 
		"icon" => "flag-checkered", 
		"code" => "f11e", 
	],
	[
		"name" => "Flag O", 
		"icon" => "flag-o", 
		"code" => "f11d", 
	],
	[
		"name" => "Flask", 
		"icon" => "flask", 
		"code" => "f0c3", 
	],
	[
		"name" => "Flickr", 
		"icon" => "flickr", 
		"code" => "f16e", 
	],
	[
		"name" => "Floppy O", 
		"icon" => "floppy-o", 
		"code" => "f0c7", 
	],
	[
		"name" => "Folder", 
		"icon" => "folder", 
		"code" => "f07b", 
	],
	[
		"name" => "Folder O", 
		"icon" => "folder-o", 
		"code" => "f114", 
	],
	[
		"name" => "Folder Open", 
		"icon" => "folder-open", 
		"code" => "f07c", 
	],
	[
		"name" => "Folder Open O", 
		"icon" => "folder-open-o", 
		"code" => "f115", 
	],
	[
		"name" => "Font", 
		"icon" => "font", 
		"code" => "f031", 
	],
	[
		"name" => "Font Awesome", 
		"icon" => "font-awesome", 
		"code" => "f2b4", 
	],
	[
		"name" => "Fonticons", 
		"icon" => "fonticons", 
		"code" => "f280", 
	],
	[
		"name" => "Fort Awesome", 
		"icon" => "fort-awesome", 
		"code" => "f286", 
	],
	[
		"name" => "Forumbee", 
		"icon" => "forumbee", 
		"code" => "f211", 
	],
	[
		"name" => "Forward", 
		"icon" => "forward", 
		"code" => "f04e", 
	],
	[
		"name" => "Foursquare", 
		"icon" => "foursquare", 
		"code" => "f180", 
	],
	[
		"name" => "Free Code Camp", 
		"icon" => "free-code-camp", 
		"code" => "f2c5", 
	],
	[
		"name" => "Frown O", 
		"icon" => "frown-o", 
		"code" => "f119", 
	],
	[
		"name" => "Futbol O", 
		"icon" => "futbol-o", 
		"code" => "f1e3", 
	],
	[
		"name" => "Gamepad", 
		"icon" => "gamepad", 
		"code" => "f11b", 
	],
	[
		"name" => "Gavel", 
		"icon" => "gavel", 
		"code" => "f0e3", 
	],
	[
		"name" => "Gbp", 
		"icon" => "gbp", 
		"code" => "f154", 
	],
	[
		"name" => "Genderless", 
		"icon" => "genderless", 
		"code" => "f22d", 
	],
	[
		"name" => "Get Pocket", 
		"icon" => "get-pocket", 
		"code" => "f265", 
	],
	[
		"name" => "Gg", 
		"icon" => "gg", 
		"code" => "f260", 
	],
	[
		"name" => "Gg Circle", 
		"icon" => "gg-circle", 
		"code" => "f261", 
	],
	[
		"name" => "Gift", 
		"icon" => "gift", 
		"code" => "f06b", 
	],
	[
		"name" => "Git", 
		"icon" => "git", 
		"code" => "f1d3", 
	],
	[
		"name" => "Git Square", 
		"icon" => "git-square", 
		"code" => "f1d2", 
	],
	[
		"name" => "Github", 
		"icon" => "github", 
		"code" => "f09b", 
	],
	[
		"name" => "Github Alt", 
		"icon" => "github-alt", 
		"code" => "f113", 
	],
	[
		"name" => "Github Square", 
		"icon" => "github-square", 
		"code" => "f092", 
	],
	[
		"name" => "Gitlab", 
		"icon" => "gitlab", 
		"code" => "f296", 
	],
	[
		"name" => "Glass", 
		"icon" => "glass", 
		"code" => "f000", 
	],
	[
		"name" => "Glide", 
		"icon" => "glide", 
		"code" => "f2a5", 
	],
	[
		"name" => "Glide G", 
		"icon" => "glide-g", 
		"code" => "f2a6", 
	],
	[
		"name" => "Globe", 
		"icon" => "globe", 
		"code" => "f0ac", 
	],
	[
		"name" => "Google", 
		"icon" => "google", 
		"code" => "f1a0", 
	],
	[
		"name" => "Google Plus", 
		"icon" => "google-plus", 
		"code" => "f0d5", 
	],
	[
		"name" => "Google Plus Official", 
		"icon" => "google-plus-official", 
		"code" => "f2b3", 
	],
	[
		"name" => "Google Plus Square", 
		"icon" => "google-plus-square", 
		"code" => "f0d4", 
	],
	[
		"name" => "Google Wallet", 
		"icon" => "google-wallet", 
		"code" => "f1ee", 
	],
	[
		"name" => "Graduation Cap", 
		"icon" => "graduation-cap", 
		"code" => "f19d", 
	],
	[
		"name" => "Gratipay", 
		"icon" => "gratipay", 
		"code" => "f184", 
	],
	[
		"name" => "Grav", 
		"icon" => "grav", 
		"code" => "f2d6", 
	],
	[
		"name" => "H Square", 
		"icon" => "h-square", 
		"code" => "f0fd", 
	],
	[
		"name" => "Hacker News", 
		"icon" => "hacker-news", 
		"code" => "f1d4", 
	],
	[
		"name" => "Hand Lizard O", 
		"icon" => "hand-lizard-o", 
		"code" => "f258", 
	],
	[
		"name" => "Hand O Down", 
		"icon" => "hand-o-down", 
		"code" => "f0a7", 
	],
	[
		"name" => "Hand O Left", 
		"icon" => "hand-o-left", 
		"code" => "f0a5", 
	],
	[
		"name" => "Hand O Right", 
		"icon" => "hand-o-right", 
		"code" => "f0a4", 
	],
	[
		"name" => "Hand O Up", 
		"icon" => "hand-o-up", 
		"code" => "f0a6", 
	],
	[
		"name" => "Hand Paper O", 
		"icon" => "hand-paper-o", 
		"code" => "f256", 
	],
	[
		"name" => "Hand Peace O", 
		"icon" => "hand-peace-o", 
		"code" => "f25b", 
	],
	[
		"name" => "Hand Pointer O", 
		"icon" => "hand-pointer-o", 
		"code" => "f25a", 
	],
	[
		"name" => "Hand Rock O", 
		"icon" => "hand-rock-o", 
		"code" => "f255", 
	],
	[
		"name" => "Hand Scissors O", 
		"icon" => "hand-scissors-o", 
		"code" => "f257", 
	],
	[
		"name" => "Hand Spock O", 
		"icon" => "hand-spock-o", 
		"code" => "f259", 
	],
	[
		"name" => "Handshake O", 
		"icon" => "handshake-o", 
		"code" => "f2b5", 
	],
	[
		"name" => "Hashtag", 
		"icon" => "hashtag", 
		"code" => "f292", 
	],
	[
		"name" => "Hdd O", 
		"icon" => "hdd-o", 
		"code" => "f0a0", 
	],
	[
		"name" => "Header", 
		"icon" => "header", 
		"code" => "f1dc", 
	],
	[
		"name" => "Headphones", 
		"icon" => "headphones", 
		"code" => "f025", 
	],
	[
		"name" => "Heart", 
		"icon" => "heart", 
		"code" => "f004", 
	],
	[
		"name" => "Heart O", 
		"icon" => "heart-o", 
		"code" => "f08a", 
	],
	[
		"name" => "Heartbeat", 
		"icon" => "heartbeat", 
		"code" => "f21e", 
	],
	[
		"name" => "History", 
		"icon" => "history", 
		"code" => "f1da", 
	],
	[
		"name" => "Home", 
		"icon" => "home", 
		"code" => "f015", 
	],
	[
		"name" => "Hospital O", 
		"icon" => "hospital-o", 
		"code" => "f0f8", 
	],
	[
		"name" => "Hourglass", 
		"icon" => "hourglass", 
		"code" => "f254", 
	],
	[
		"name" => "Hourglass End", 
		"icon" => "hourglass-end", 
		"code" => "f253", 
	],
	[
		"name" => "Hourglass Half", 
		"icon" => "hourglass-half", 
		"code" => "f252", 
	],
	[
		"name" => "Hourglass O", 
		"icon" => "hourglass-o", 
		"code" => "f250", 
	],
	[
		"name" => "Hourglass Start", 
		"icon" => "hourglass-start", 
		"code" => "f251", 
	],
	[
		"name" => "Houzz", 
		"icon" => "houzz", 
		"code" => "f27c", 
	],
	[
		"name" => "Html5", 
		"icon" => "html5", 
		"code" => "f13b", 
	],
	[
		"name" => "I Cursor", 
		"icon" => "i-cursor", 
		"code" => "f246", 
	],
	[
		"name" => "Id Badge", 
		"icon" => "id-badge", 
		"code" => "f2c1", 
	],
	[
		"name" => "Id Card", 
		"icon" => "id-card", 
		"code" => "f2c2", 
	],
	[
		"name" => "Id Card O", 
		"icon" => "id-card-o", 
		"code" => "f2c3", 
	],
	[
		"name" => "Ils", 
		"icon" => "ils", 
		"code" => "f20b", 
	],
	[
		"name" => "Imdb", 
		"icon" => "imdb", 
		"code" => "f2d8", 
	],
	[
		"name" => "Inbox", 
		"icon" => "inbox", 
		"code" => "f01c", 
	],
	[
		"name" => "Indent", 
		"icon" => "indent", 
		"code" => "f03c", 
	],
	[
		"name" => "Industry", 
		"icon" => "industry", 
		"code" => "f275", 
	],
	[
		"name" => "Info", 
		"icon" => "info", 
		"code" => "f129", 
	],
	[
		"name" => "Info Circle", 
		"icon" => "info-circle", 
		"code" => "f05a", 
	],
	[
		"name" => "Inr", 
		"icon" => "inr", 
		"code" => "f156", 
	],
	[
		"name" => "Instagram", 
		"icon" => "instagram", 
		"code" => "f16d", 
	],
	[
		"name" => "Internet Explorer", 
		"icon" => "internet-explorer", 
		"code" => "f26b", 
	],
	[
		"name" => "Ioxhost", 
		"icon" => "ioxhost", 
		"code" => "f208", 
	],
	[
		"name" => "Italic", 
		"icon" => "italic", 
		"code" => "f033", 
	],
	[
		"name" => "Joomla", 
		"icon" => "joomla", 
		"code" => "f1aa", 
	],
	[
		"name" => "Jpy", 
		"icon" => "jpy", 
		"code" => "f157", 
	],
	[
		"name" => "Jsfiddle", 
		"icon" => "jsfiddle", 
		"code" => "f1cc", 
	],
	[
		"name" => "Key", 
		"icon" => "key", 
		"code" => "f084", 
	],
	[
		"name" => "Keyboard O", 
		"icon" => "keyboard-o", 
		"code" => "f11c", 
	],
	[
		"name" => "Krw", 
		"icon" => "krw", 
		"code" => "f159", 
	],
	[
		"name" => "Language", 
		"icon" => "language", 
		"code" => "f1ab", 
	],
	[
		"name" => "Laptop", 
		"icon" => "laptop", 
		"code" => "f109", 
	],
	[
		"name" => "Lastfm", 
		"icon" => "lastfm", 
		"code" => "f202", 
	],
	[
		"name" => "Lastfm Square", 
		"icon" => "lastfm-square", 
		"code" => "f203", 
	],
	[
		"name" => "Leaf", 
		"icon" => "leaf", 
		"code" => "f06c", 
	],
	[
		"name" => "Leanpub", 
		"icon" => "leanpub", 
		"code" => "f212", 
	],
	[
		"name" => "Lemon O", 
		"icon" => "lemon-o", 
		"code" => "f094", 
	],
	[
		"name" => "Level Down", 
		"icon" => "level-down", 
		"code" => "f149", 
	],
	[
		"name" => "Level Up", 
		"icon" => "level-up", 
		"code" => "f148", 
	],
	[
		"name" => "Life Ring", 
		"icon" => "life-ring", 
		"code" => "f1cd", 
	],
	[
		"name" => "Lightbulb O", 
		"icon" => "lightbulb-o", 
		"code" => "f0eb", 
	],
	[
		"name" => "Line Chart", 
		"icon" => "line-chart", 
		"code" => "f201", 
	],
	[
		"name" => "Link", 
		"icon" => "link", 
		"code" => "f0c1", 
	],
	[
		"name" => "Linkedin", 
		"icon" => "linkedin", 
		"code" => "f0e1", 
	],
	[
		"name" => "Linkedin Square", 
		"icon" => "linkedin-square", 
		"code" => "f08c", 
	],
	[
		"name" => "Linode", 
		"icon" => "linode", 
		"code" => "f2b8", 
	],
	[
		"name" => "Linux", 
		"icon" => "linux", 
		"code" => "f17c", 
	],
	[
		"name" => "List", 
		"icon" => "list", 
		"code" => "f03a", 
	],
	[
		"name" => "List Alt", 
		"icon" => "list-alt", 
		"code" => "f022", 
	],
	[
		"name" => "List Ol", 
		"icon" => "list-ol", 
		"code" => "f0cb", 
	],
	[
		"name" => "List Ul", 
		"icon" => "list-ul", 
		"code" => "f0ca", 
	],
	[
		"name" => "Location Arrow", 
		"icon" => "location-arrow", 
		"code" => "f124", 
	],
	[
		"name" => "Lock", 
		"icon" => "lock", 
		"code" => "f023", 
	],
	[
		"name" => "Long Arrow Down", 
		"icon" => "long-arrow-down", 
		"code" => "f175", 
	],
	[
		"name" => "Long Arrow Left", 
		"icon" => "long-arrow-left", 
		"code" => "f177", 
	],
	[
		"name" => "Long Arrow Right", 
		"icon" => "long-arrow-right", 
		"code" => "f178", 
	],
	[
		"name" => "Long Arrow Up", 
		"icon" => "long-arrow-up", 
		"code" => "f176", 
	],
	[
		"name" => "Low Vision", 
		"icon" => "low-vision", 
		"code" => "f2a8", 
	],
	[
		"name" => "Magic", 
		"icon" => "magic", 
		"code" => "f0d0", 
	],
	[
		"name" => "Magnet", 
		"icon" => "magnet", 
		"code" => "f076", 
	],
	[
		"name" => "Male", 
		"icon" => "male", 
		"code" => "f183", 
	],
	[
		"name" => "Map", 
		"icon" => "map", 
		"code" => "f279", 
	],
	[
		"name" => "Map Marker", 
		"icon" => "map-marker", 
		"code" => "f041", 
	],
	[
		"name" => "Map O", 
		"icon" => "map-o", 
		"code" => "f278", 
	],
	[
		"name" => "Map Pin", 
		"icon" => "map-pin", 
		"code" => "f276", 
	],
	[
		"name" => "Map Signs", 
		"icon" => "map-signs", 
		"code" => "f277", 
	],
	[
		"name" => "Mars", 
		"icon" => "mars", 
		"code" => "f222", 
	],
	[
		"name" => "Mars Double", 
		"icon" => "mars-double", 
		"code" => "f227", 
	],
	[
		"name" => "Mars Stroke", 
		"icon" => "mars-stroke", 
		"code" => "f229", 
	],
	[
		"name" => "Mars Stroke H", 
		"icon" => "mars-stroke-h", 
		"code" => "f22b", 
	],
	[
		"name" => "Mars Stroke V", 
		"icon" => "mars-stroke-v", 
		"code" => "f22a", 
	],
	[
		"name" => "Maxcdn", 
		"icon" => "maxcdn", 
		"code" => "f136", 
	],
	[
		"name" => "Meanpath", 
		"icon" => "meanpath", 
		"code" => "f20c", 
	],
	[
		"name" => "Medium", 
		"icon" => "medium", 
		"code" => "f23a", 
	],
	[
		"name" => "Medkit", 
		"icon" => "medkit", 
		"code" => "f0fa", 
	],
	[
		"name" => "Meetup", 
		"icon" => "meetup", 
		"code" => "f2e0", 
	],
	[
		"name" => "Meh O", 
		"icon" => "meh-o", 
		"code" => "f11a", 
	],
	[
		"name" => "Mercury", 
		"icon" => "mercury", 
		"code" => "f223", 
	],
	[
		"name" => "Microchip", 
		"icon" => "microchip", 
		"code" => "f2db", 
	],
	[
		"name" => "Microphone", 
		"icon" => "microphone", 
		"code" => "f130", 
	],
	[
		"name" => "Microphone Slash", 
		"icon" => "microphone-slash", 
		"code" => "f131", 
	],
	[
		"name" => "Minus", 
		"icon" => "minus", 
		"code" => "f068", 
	],
	[
		"name" => "Minus Circle", 
		"icon" => "minus-circle", 
		"code" => "f056", 
	],
	[
		"name" => "Minus Square", 
		"icon" => "minus-square", 
		"code" => "f146", 
	],
	[
		"name" => "Minus Square O", 
		"icon" => "minus-square-o", 
		"code" => "f147", 
	],
	[
		"name" => "Mixcloud", 
		"icon" => "mixcloud", 
		"code" => "f289", 
	],
	[
		"name" => "Mobile", 
		"icon" => "mobile", 
		"code" => "f10b", 
	],
	[
		"name" => "Modx", 
		"icon" => "modx", 
		"code" => "f285", 
	],
	[
		"name" => "Money", 
		"icon" => "money", 
		"code" => "f0d6", 
	],
	[
		"name" => "Moon O", 
		"icon" => "moon-o", 
		"code" => "f186", 
	],
	[
		"name" => "Motorcycle", 
		"icon" => "motorcycle", 
		"code" => "f21c", 
	],
	[
		"name" => "Mouse Pointer", 
		"icon" => "mouse-pointer", 
		"code" => "f245", 
	],
	[
		"name" => "Music", 
		"icon" => "music", 
		"code" => "f001", 
	],
	[
		"name" => "Neuter", 
		"icon" => "neuter", 
		"code" => "f22c", 
	],
	[
		"name" => "Newspaper O", 
		"icon" => "newspaper-o", 
		"code" => "f1ea", 
	],
	[
		"name" => "Object Group", 
		"icon" => "object-group", 
		"code" => "f247", 
	],
	[
		"name" => "Object Ungroup", 
		"icon" => "object-ungroup", 
		"code" => "f248", 
	],
	[
		"name" => "Odnoklassniki", 
		"icon" => "odnoklassniki", 
		"code" => "f263", 
	],
	[
		"name" => "Odnoklassniki Square", 
		"icon" => "odnoklassniki-square", 
		"code" => "f264", 
	],
	[
		"name" => "Opencart", 
		"icon" => "opencart", 
		"code" => "f23d", 
	],
	[
		"name" => "Openid", 
		"icon" => "openid", 
		"code" => "f19b", 
	],
	[
		"name" => "Opera", 
		"icon" => "opera", 
		"code" => "f26a", 
	],
	[
		"name" => "Optin Monster", 
		"icon" => "optin-monster", 
		"code" => "f23c", 
	],
	[
		"name" => "Outdent", 
		"icon" => "outdent", 
		"code" => "f03b", 
	],
	[
		"name" => "Pagelines", 
		"icon" => "pagelines", 
		"code" => "f18c", 
	],
	[
		"name" => "Paint Brush", 
		"icon" => "paint-brush", 
		"code" => "f1fc", 
	],
	[
		"name" => "Paper Plane", 
		"icon" => "paper-plane", 
		"code" => "f1d8", 
	],
	[
		"name" => "Paper Plane O", 
		"icon" => "paper-plane-o", 
		"code" => "f1d9", 
	],
	[
		"name" => "Paperclip", 
		"icon" => "paperclip", 
		"code" => "f0c6", 
	],
	[
		"name" => "Paragraph", 
		"icon" => "paragraph", 
		"code" => "f1dd", 
	],
	[
		"name" => "Pause", 
		"icon" => "pause", 
		"code" => "f04c", 
	],
	[
		"name" => "Pause Circle", 
		"icon" => "pause-circle", 
		"code" => "f28b", 
	],
	[
		"name" => "Pause Circle O", 
		"icon" => "pause-circle-o", 
		"code" => "f28c", 
	],
	[
		"name" => "Paw", 
		"icon" => "paw", 
		"code" => "f1b0", 
	],
	[
		"name" => "Paypal", 
		"icon" => "paypal", 
		"code" => "f1ed", 
	],
	[
		"name" => "Pencil", 
		"icon" => "pencil", 
		"code" => "f040", 
	],
	[
		"name" => "Pencil Square", 
		"icon" => "pencil-square", 
		"code" => "f14b", 
	],
	[
		"name" => "Pencil Square O", 
		"icon" => "pencil-square-o", 
		"code" => "f044", 
	],
	[
		"name" => "Percent", 
		"icon" => "percent", 
		"code" => "f295", 
	],
	[
		"name" => "Phone", 
		"icon" => "phone", 
		"code" => "f095", 
	],
	[
		"name" => "Phone Square", 
		"icon" => "phone-square", 
		"code" => "f098", 
	],
	[
		"name" => "Picture O", 
		"icon" => "picture-o", 
		"code" => "f03e", 
	],
	[
		"name" => "Pie Chart", 
		"icon" => "pie-chart", 
		"code" => "f200", 
	],
	[
		"name" => "Pied Piper", 
		"icon" => "pied-piper", 
		"code" => "f2ae", 
	],
	[
		"name" => "Pied Piper Alt", 
		"icon" => "pied-piper-alt", 
		"code" => "f1a8", 
	],
	[
		"name" => "Pied Piper Pp", 
		"icon" => "pied-piper-pp", 
		"code" => "f1a7", 
	],
	[
		"name" => "Pinterest", 
		"icon" => "pinterest", 
		"code" => "f0d2", 
	],
	[
		"name" => "Pinterest P", 
		"icon" => "pinterest-p", 
		"code" => "f231", 
	],
	[
		"name" => "Pinterest Square", 
		"icon" => "pinterest-square", 
		"code" => "f0d3", 
	],
	[
		"name" => "Plane", 
		"icon" => "plane", 
		"code" => "f072", 
	],
	[
		"name" => "Play", 
		"icon" => "play", 
		"code" => "f04b", 
	],
	[
		"name" => "Play Circle", 
		"icon" => "play-circle", 
		"code" => "f144", 
	],
	[
		"name" => "Play Circle O", 
		"icon" => "play-circle-o", 
		"code" => "f01d", 
	],
	[
		"name" => "Plug", 
		"icon" => "plug", 
		"code" => "f1e6", 
	],
	[
		"name" => "Plus", 
		"icon" => "plus", 
		"code" => "f067", 
	],
	[
		"name" => "Plus Circle", 
		"icon" => "plus-circle", 
		"code" => "f055", 
	],
	[
		"name" => "Plus Square", 
		"icon" => "plus-square", 
		"code" => "f0fe", 
	],
	[
		"name" => "Plus Square O", 
		"icon" => "plus-square-o", 
		"code" => "f196", 
	],
	[
		"name" => "Podcast", 
		"icon" => "podcast", 
		"code" => "f2ce", 
	],
	[
		"name" => "Power Off", 
		"icon" => "power-off", 
		"code" => "f011", 
	],
	[
		"name" => "Print", 
		"icon" => "print", 
		"code" => "f02f", 
	],
	[
		"name" => "Product Hunt", 
		"icon" => "product-hunt", 
		"code" => "f288", 
	],
	[
		"name" => "Puzzle Piece", 
		"icon" => "puzzle-piece", 
		"code" => "f12e", 
	],
	[
		"name" => "Qq", 
		"icon" => "qq", 
		"code" => "f1d6", 
	],
	[
		"name" => "Qrcode", 
		"icon" => "qrcode", 
		"code" => "f029", 
	],
	[
		"name" => "Question", 
		"icon" => "question", 
		"code" => "f128", 
	],
	[
		"name" => "Question Circle", 
		"icon" => "question-circle", 
		"code" => "f059", 
	],
	[
		"name" => "Question Circle O", 
		"icon" => "question-circle-o", 
		"code" => "f29c", 
	],
	[
		"name" => "Quora", 
		"icon" => "quora", 
		"code" => "f2c4", 
	],
	[
		"name" => "Quote Left", 
		"icon" => "quote-left", 
		"code" => "f10d", 
	],
	[
		"name" => "Quote Right", 
		"icon" => "quote-right", 
		"code" => "f10e", 
	],
	[
		"name" => "Random", 
		"icon" => "random", 
		"code" => "f074", 
	],
	[
		"name" => "Ravelry", 
		"icon" => "ravelry", 
		"code" => "f2d9", 
	],
	[
		"name" => "Rebel", 
		"icon" => "rebel", 
		"code" => "f1d0", 
	],
	[
		"name" => "Recycle", 
		"icon" => "recycle", 
		"code" => "f1b8", 
	],
	[
		"name" => "Reddit", 
		"icon" => "reddit", 
		"code" => "f1a1", 
	],
	[
		"name" => "Reddit Alien", 
		"icon" => "reddit-alien", 
		"code" => "f281", 
	],
	[
		"name" => "Reddit Square", 
		"icon" => "reddit-square", 
		"code" => "f1a2", 
	],
	[
		"name" => "Refresh", 
		"icon" => "refresh", 
		"code" => "f021", 
	],
	[
		"name" => "Registered", 
		"icon" => "registered", 
		"code" => "f25d", 
	],
	[
		"name" => "Renren", 
		"icon" => "renren", 
		"code" => "f18b", 
	],
	[
		"name" => "Repeat", 
		"icon" => "repeat", 
		"code" => "f01e", 
	],
	[
		"name" => "Reply", 
		"icon" => "reply", 
		"code" => "f112", 
	],
	[
		"name" => "Reply All", 
		"icon" => "reply-all", 
		"code" => "f122", 
	],
	[
		"name" => "Retweet", 
		"icon" => "retweet", 
		"code" => "f079", 
	],
	[
		"name" => "Road", 
		"icon" => "road", 
		"code" => "f018", 
	],
	[
		"name" => "Rocket", 
		"icon" => "rocket", 
		"code" => "f135", 
	],
	[
		"name" => "Rss", 
		"icon" => "rss", 
		"code" => "f09e", 
	],
	[
		"name" => "Rss Square", 
		"icon" => "rss-square", 
		"code" => "f143", 
	],
	[
		"name" => "Rub", 
		"icon" => "rub", 
		"code" => "f158", 
	],
	[
		"name" => "Safari", 
		"icon" => "safari", 
		"code" => "f267", 
	],
	[
		"name" => "Scissors", 
		"icon" => "scissors", 
		"code" => "f0c4", 
	],
	[
		"name" => "Scribd", 
		"icon" => "scribd", 
		"code" => "f28a", 
	],
	[
		"name" => "Search", 
		"icon" => "search", 
		"code" => "f002", 
	],
	[
		"name" => "Search Minus", 
		"icon" => "search-minus", 
		"code" => "f010", 
	],
	[
		"name" => "Search Plus", 
		"icon" => "search-plus", 
		"code" => "f00e", 
	],
	[
		"name" => "Sellsy", 
		"icon" => "sellsy", 
		"code" => "f213", 
	],
	[
		"name" => "Server", 
		"icon" => "server", 
		"code" => "f233", 
	],
	[
		"name" => "Share", 
		"icon" => "share", 
		"code" => "f064", 
	],
	[
		"name" => "Share Alt", 
		"icon" => "share-alt", 
		"code" => "f1e0", 
	],
	[
		"name" => "Share Alt Square", 
		"icon" => "share-alt-square", 
		"code" => "f1e1", 
	],
	[
		"name" => "Share Square", 
		"icon" => "share-square", 
		"code" => "f14d", 
	],
	[
		"name" => "Share Square O", 
		"icon" => "share-square-o", 
		"code" => "f045", 
	],
	[
		"name" => "Shield", 
		"icon" => "shield", 
		"code" => "f132", 
	],
	[
		"name" => "Ship", 
		"icon" => "ship", 
		"code" => "f21a", 
	],
	[
		"name" => "Shirtsinbulk", 
		"icon" => "shirtsinbulk", 
		"code" => "f214", 
	],
	[
		"name" => "Shopping Bag", 
		"icon" => "shopping-bag", 
		"code" => "f290", 
	],
	[
		"name" => "Shopping Basket", 
		"icon" => "shopping-basket", 
		"code" => "f291", 
	],
	[
		"name" => "Shopping Cart", 
		"icon" => "shopping-cart", 
		"code" => "f07a", 
	],
	[
		"name" => "Shower", 
		"icon" => "shower", 
		"code" => "f2cc", 
	],
	[
		"name" => "Sign In", 
		"icon" => "sign-in", 
		"code" => "f090", 
	],
	[
		"name" => "Sign Language", 
		"icon" => "sign-language", 
		"code" => "f2a7", 
	],
	[
		"name" => "Sign Out", 
		"icon" => "sign-out", 
		"code" => "f08b", 
	],
	[
		"name" => "Signal", 
		"icon" => "signal", 
		"code" => "f012", 
	],
	[
		"name" => "Simplybuilt", 
		"icon" => "simplybuilt", 
		"code" => "f215", 
	],
	[
		"name" => "Sitemap", 
		"icon" => "sitemap", 
		"code" => "f0e8", 
	],
	[
		"name" => "Skyatlas", 
		"icon" => "skyatlas", 
		"code" => "f216", 
	],
	[
		"name" => "Skype", 
		"icon" => "skype", 
		"code" => "f17e", 
	],
	[
		"name" => "Slack", 
		"icon" => "slack", 
		"code" => "f198", 
	],
	[
		"name" => "Sliders", 
		"icon" => "sliders", 
		"code" => "f1de", 
	],
	[
		"name" => "Slideshare", 
		"icon" => "slideshare", 
		"code" => "f1e7", 
	],
	[
		"name" => "Smile O", 
		"icon" => "smile-o", 
		"code" => "f118", 
	],
	[
		"name" => "Snapchat", 
		"icon" => "snapchat", 
		"code" => "f2ab", 
	],
	[
		"name" => "Snapchat Ghost", 
		"icon" => "snapchat-ghost", 
		"code" => "f2ac", 
	],
	[
		"name" => "Snapchat Square", 
		"icon" => "snapchat-square", 
		"code" => "f2ad", 
	],
	[
		"name" => "Snowflake O", 
		"icon" => "snowflake-o", 
		"code" => "f2dc", 
	],
	[
		"name" => "Sort", 
		"icon" => "sort", 
		"code" => "f0dc", 
	],
	[
		"name" => "Sort Alpha Asc", 
		"icon" => "sort-alpha-asc", 
		"code" => "f15d", 
	],
	[
		"name" => "Sort Alpha Desc", 
		"icon" => "sort-alpha-desc", 
		"code" => "f15e", 
	],
	[
		"name" => "Sort Amount Asc", 
		"icon" => "sort-amount-asc", 
		"code" => "f160", 
	],
	[
		"name" => "Sort Amount Desc", 
		"icon" => "sort-amount-desc", 
		"code" => "f161", 
	],
	[
		"name" => "Sort Asc", 
		"icon" => "sort-asc", 
		"code" => "f0de", 
	],
	[
		"name" => "Sort Desc", 
		"icon" => "sort-desc", 
		"code" => "f0dd", 
	],
	[
		"name" => "Sort Numeric Asc", 
		"icon" => "sort-numeric-asc", 
		"code" => "f162", 
	],
	[
		"name" => "Sort Numeric Desc", 
		"icon" => "sort-numeric-desc", 
		"code" => "f163", 
	],
	[
		"name" => "Soundcloud", 
		"icon" => "soundcloud", 
		"code" => "f1be", 
	],
	[
		"name" => "Space Shuttle", 
		"icon" => "space-shuttle", 
		"code" => "f197", 
	],
	[
		"name" => "Spinner", 
		"icon" => "spinner", 
		"code" => "f110", 
	],
	[
		"name" => "Spoon", 
		"icon" => "spoon", 
		"code" => "f1b1", 
	],
	[
		"name" => "Spotify", 
		"icon" => "spotify", 
		"code" => "f1bc", 
	],
	[
		"name" => "Square", 
		"icon" => "square", 
		"code" => "f0c8", 
	],
	[
		"name" => "Square O", 
		"icon" => "square-o", 
		"code" => "f096", 
	],
	[
		"name" => "Stack Exchange", 
		"icon" => "stack-exchange", 
		"code" => "f18d", 
	],
	[
		"name" => "Stack Overflow", 
		"icon" => "stack-overflow", 
		"code" => "f16c", 
	],
	[
		"name" => "Star", 
		"icon" => "star", 
		"code" => "f005", 
	],
	[
		"name" => "Star Half", 
		"icon" => "star-half", 
		"code" => "f089", 
	],
	[
		"name" => "Star Half O", 
		"icon" => "star-half-o", 
		"code" => "f123", 
	],
	[
		"name" => "Star O", 
		"icon" => "star-o", 
		"code" => "f006", 
	],
	[
		"name" => "Steam", 
		"icon" => "steam", 
		"code" => "f1b6", 
	],
	[
		"name" => "Steam Square", 
		"icon" => "steam-square", 
		"code" => "f1b7", 
	],
	[
		"name" => "Step Backward", 
		"icon" => "step-backward", 
		"code" => "f048", 
	],
	[
		"name" => "Step Forward", 
		"icon" => "step-forward", 
		"code" => "f051", 
	],
	[
		"name" => "Stethoscope", 
		"icon" => "stethoscope", 
		"code" => "f0f1", 
	],
	[
		"name" => "Sticky Note", 
		"icon" => "sticky-note", 
		"code" => "f249", 
	],
	[
		"name" => "Sticky Note O", 
		"icon" => "sticky-note-o", 
		"code" => "f24a", 
	],
	[
		"name" => "Stop", 
		"icon" => "stop", 
		"code" => "f04d", 
	],
	[
		"name" => "Stop Circle", 
		"icon" => "stop-circle", 
		"code" => "f28d", 
	],
	[
		"name" => "Stop Circle O", 
		"icon" => "stop-circle-o", 
		"code" => "f28e", 
	],
	[
		"name" => "Street View", 
		"icon" => "street-view", 
		"code" => "f21d", 
	],
	[
		"name" => "Strikethrough", 
		"icon" => "strikethrough", 
		"code" => "f0cc", 
	],
	[
		"name" => "Stumbleupon", 
		"icon" => "stumbleupon", 
		"code" => "f1a4", 
	],
	[
		"name" => "Stumbleupon Circle", 
		"icon" => "stumbleupon-circle", 
		"code" => "f1a3", 
	],
	[
		"name" => "Subscript", 
		"icon" => "subscript", 
		"code" => "f12c", 
	],
	[
		"name" => "Subway", 
		"icon" => "subway", 
		"code" => "f239", 
	],
	[
		"name" => "Suitcase", 
		"icon" => "suitcase", 
		"code" => "f0f2", 
	],
	[
		"name" => "Sun O", 
		"icon" => "sun-o", 
		"code" => "f185", 
	],
	[
		"name" => "Superpowers", 
		"icon" => "superpowers", 
		"code" => "f2dd", 
	],
	[
		"name" => "Superscript", 
		"icon" => "superscript", 
		"code" => "f12b", 
	],
	[
		"name" => "Table", 
		"icon" => "table", 
		"code" => "f0ce", 
	],
	[
		"name" => "Tablet", 
		"icon" => "tablet", 
		"code" => "f10a", 
	],
	[
		"name" => "Tachometer", 
		"icon" => "tachometer", 
		"code" => "f0e4", 
	],
	[
		"name" => "Tag", 
		"icon" => "tag", 
		"code" => "f02b", 
	],
	[
		"name" => "Tags", 
		"icon" => "tags", 
		"code" => "f02c", 
	],
	[
		"name" => "Tasks", 
		"icon" => "tasks", 
		"code" => "f0ae", 
	],
	[
		"name" => "Taxi", 
		"icon" => "taxi", 
		"code" => "f1ba", 
	],
	[
		"name" => "Telegram", 
		"icon" => "telegram", 
		"code" => "f2c6", 
	],
	[
		"name" => "Television", 
		"icon" => "television", 
		"code" => "f26c", 
	],
	[
		"name" => "Tencent Weibo", 
		"icon" => "tencent-weibo", 
		"code" => "f1d5", 
	],
	[
		"name" => "Terminal", 
		"icon" => "terminal", 
		"code" => "f120", 
	],
	[
		"name" => "Text Height", 
		"icon" => "text-height", 
		"code" => "f034", 
	],
	[
		"name" => "Text Width", 
		"icon" => "text-width", 
		"code" => "f035", 
	],
	[
		"name" => "Th", 
		"icon" => "th", 
		"code" => "f00a", 
	],
	[
		"name" => "Th Large", 
		"icon" => "th-large", 
		"code" => "f009", 
	],
	[
		"name" => "Th List", 
		"icon" => "th-list", 
		"code" => "f00b", 
	],
	[
		"name" => "Themeisle", 
		"icon" => "themeisle", 
		"code" => "f2b2", 
	],
	[
		"name" => "Thermometer Empty", 
		"icon" => "thermometer-empty", 
		"code" => "f2cb", 
	],
	[
		"name" => "Thermometer Full", 
		"icon" => "thermometer-full", 
		"code" => "f2c7", 
	],
	[
		"name" => "Thermometer Half", 
		"icon" => "thermometer-half", 
		"code" => "f2c9", 
	],
	[
		"name" => "Thermometer Quarter", 
		"icon" => "thermometer-quarter", 
		"code" => "f2ca", 
	],
	[
		"name" => "Thermometer Three Quarters", 
		"icon" => "thermometer-three-quarters", 
		"code" => "f2c8", 
	],
	[
		"name" => "Thumb Tack", 
		"icon" => "thumb-tack", 
		"code" => "f08d", 
	],
	[
		"name" => "Thumbs Down", 
		"icon" => "thumbs-down", 
		"code" => "f165", 
	],
	[
		"name" => "Thumbs O Down", 
		"icon" => "thumbs-o-down", 
		"code" => "f088", 
	],
	[
		"name" => "Thumbs O Up", 
		"icon" => "thumbs-o-up", 
		"code" => "f087", 
	],
	[
		"name" => "Thumbs Up", 
		"icon" => "thumbs-up", 
		"code" => "f164", 
	],
	[
		"name" => "Ticket", 
		"icon" => "ticket", 
		"code" => "f145", 
	],
	[
		"name" => "Times", 
		"icon" => "times", 
		"code" => "f00d", 
	],
	[
		"name" => "Times Circle", 
		"icon" => "times-circle", 
		"code" => "f057", 
	],
	[
		"name" => "Times Circle O", 
		"icon" => "times-circle-o", 
		"code" => "f05c", 
	],
	[
		"name" => "Tint", 
		"icon" => "tint", 
		"code" => "f043", 
	],
	[
		"name" => "Toggle Off", 
		"icon" => "toggle-off", 
		"code" => "f204", 
	],
	[
		"name" => "Toggle On", 
		"icon" => "toggle-on", 
		"code" => "f205", 
	],
	[
		"name" => "Trademark", 
		"icon" => "trademark", 
		"code" => "f25c", 
	],
	[
		"name" => "Train", 
		"icon" => "train", 
		"code" => "f238", 
	],
	[
		"name" => "Transgender", 
		"icon" => "transgender", 
		"code" => "f224", 
	],
	[
		"name" => "Transgender Alt", 
		"icon" => "transgender-alt", 
		"code" => "f225", 
	],
	[
		"name" => "Trash", 
		"icon" => "trash", 
		"code" => "f1f8", 
	],
	[
		"name" => "Trash O", 
		"icon" => "trash-o", 
		"code" => "f014", 
	],
	[
		"name" => "Tree", 
		"icon" => "tree", 
		"code" => "f1bb", 
	],
	[
		"name" => "Trello", 
		"icon" => "trello", 
		"code" => "f181", 
	],
	[
		"name" => "Tripadvisor", 
		"icon" => "tripadvisor", 
		"code" => "f262", 
	],
	[
		"name" => "Trophy", 
		"icon" => "trophy", 
		"code" => "f091", 
	],
	[
		"name" => "Truck", 
		"icon" => "truck", 
		"code" => "f0d1", 
	],
	[
		"name" => "Try", 
		"icon" => "try", 
		"code" => "f195", 
	],
	[
		"name" => "Tty", 
		"icon" => "tty", 
		"code" => "f1e4", 
	],
	[
		"name" => "Tumblr", 
		"icon" => "tumblr", 
		"code" => "f173", 
	],
	[
		"name" => "Tumblr Square", 
		"icon" => "tumblr-square", 
		"code" => "f174", 
	],
	[
		"name" => "Twitch", 
		"icon" => "twitch", 
		"code" => "f1e8", 
	],
	[
		"name" => "Twitter", 
		"icon" => "twitter", 
		"code" => "f099", 
	],
	[
		"name" => "Twitter Square", 
		"icon" => "twitter-square", 
		"code" => "f081", 
	],
	[
		"name" => "Umbrella", 
		"icon" => "umbrella", 
		"code" => "f0e9", 
	],
	[
		"name" => "Underline", 
		"icon" => "underline", 
		"code" => "f0cd", 
	],
	[
		"name" => "Undo", 
		"icon" => "undo", 
		"code" => "f0e2", 
	],
	[
		"name" => "Universal Access", 
		"icon" => "universal-access", 
		"code" => "f29a", 
	],
	[
		"name" => "University", 
		"icon" => "university", 
		"code" => "f19c", 
	],
	[
		"name" => "Unlock", 
		"icon" => "unlock", 
		"code" => "f09c", 
	],
	[
		"name" => "Unlock Alt", 
		"icon" => "unlock-alt", 
		"code" => "f13e", 
	],
	[
		"name" => "Upload", 
		"icon" => "upload", 
		"code" => "f093", 
	],
	[
		"name" => "Usb", 
		"icon" => "usb", 
		"code" => "f287", 
	],
	[
		"name" => "Usd", 
		"icon" => "usd", 
		"code" => "f155", 
	],
	[
		"name" => "User", 
		"icon" => "user", 
		"code" => "f007", 
	],
	[
		"name" => "User Circle", 
		"icon" => "user-circle", 
		"code" => "f2bd", 
	],
	[
		"name" => "User Circle O", 
		"icon" => "user-circle-o", 
		"code" => "f2be", 
	],
	[
		"name" => "User Md", 
		"icon" => "user-md", 
		"code" => "f0f0", 
	],
	[
		"name" => "User O", 
		"icon" => "user-o", 
		"code" => "f2c0", 
	],
	[
		"name" => "User Plus", 
		"icon" => "user-plus", 
		"code" => "f234", 
	],
	[
		"name" => "User Secret", 
		"icon" => "user-secret", 
		"code" => "f21b", 
	],
	[
		"name" => "User Times", 
		"icon" => "user-times", 
		"code" => "f235", 
	],
	[
		"name" => "Users", 
		"icon" => "users", 
		"code" => "f0c0", 
	],
	[
		"name" => "Venus", 
		"icon" => "venus", 
		"code" => "f221", 
	],
	[
		"name" => "Venus Double", 
		"icon" => "venus-double", 
		"code" => "f226", 
	],
	[
		"name" => "Venus Mars", 
		"icon" => "venus-mars", 
		"code" => "f228", 
	],
	[
		"name" => "Viacoin", 
		"icon" => "viacoin", 
		"code" => "f237", 
	],
	[
		"name" => "Viadeo", 
		"icon" => "viadeo", 
		"code" => "f2a9", 
	],
	[
		"name" => "Viadeo Square", 
		"icon" => "viadeo-square", 
		"code" => "f2aa", 
	],
	[
		"name" => "Video Camera", 
		"icon" => "video-camera", 
		"code" => "f03d", 
	],
	[
		"name" => "Vimeo", 
		"icon" => "vimeo", 
		"code" => "f27d", 
	],
	[
		"name" => "Vimeo Square", 
		"icon" => "vimeo-square", 
		"code" => "f194", 
	],
	[
		"name" => "Vine", 
		"icon" => "vine", 
		"code" => "f1ca", 
	],
	[
		"name" => "Vk", 
		"icon" => "vk", 
		"code" => "f189", 
	],
	[
		"name" => "Volume Control Phone", 
		"icon" => "volume-control-phone", 
		"code" => "f2a0", 
	],
	[
		"name" => "Volume Down", 
		"icon" => "volume-down", 
		"code" => "f027", 
	],
	[
		"name" => "Volume Off", 
		"icon" => "volume-off", 
		"code" => "f026", 
	],
	[
		"name" => "Volume Up", 
		"icon" => "volume-up", 
		"code" => "f028", 
	],
	[
		"name" => "Weibo", 
		"icon" => "weibo", 
		"code" => "f18a", 
	],
	[
		"name" => "Weixin", 
		"icon" => "weixin", 
		"code" => "f1d7", 
	],
	[
		"name" => "Whatsapp", 
		"icon" => "whatsapp", 
		"code" => "f232", 
	],
	[
		"name" => "Wheelchair", 
		"icon" => "wheelchair", 
		"code" => "f193", 
	],
	[
		"name" => "Wheelchair Alt", 
		"icon" => "wheelchair-alt", 
		"code" => "f29b", 
	],
	[
		"name" => "Wifi", 
		"icon" => "wifi", 
		"code" => "f1eb", 
	],
	[
		"name" => "Wikipedia W", 
		"icon" => "wikipedia-w", 
		"code" => "f266", 
	],
	[
		"name" => "Window Close", 
		"icon" => "window-close", 
		"code" => "f2d3", 
	],
	[
		"name" => "Window Close O", 
		"icon" => "window-close-o", 
		"code" => "f2d4", 
	],
	[
		"name" => "Window Maximize", 
		"icon" => "window-maximize", 
		"code" => "f2d0", 
	],
	[
		"name" => "Window Minimize", 
		"icon" => "window-minimize", 
		"code" => "f2d1", 
	],
	[
		"name" => "Window Restore", 
		"icon" => "window-restore", 
		"code" => "f2d2", 
	],
	[
		"name" => "Windows", 
		"icon" => "windows", 
		"code" => "f17a", 
	],
	[
		"name" => "Wordpress", 
		"icon" => "wordpress", 
		"code" => "f19a", 
	],
	[
		"name" => "Wpbeginner", 
		"icon" => "wpbeginner", 
		"code" => "f297", 
	],
	[
		"name" => "Wpexplorer", 
		"icon" => "wpexplorer", 
		"code" => "f2de", 
	],
	[
		"name" => "Wpforms", 
		"icon" => "wpforms", 
		"code" => "f298", 
	],
	[
		"name" => "Wrench", 
		"icon" => "wrench", 
		"code" => "f0ad", 
	],
	[
		"name" => "Xing", 
		"icon" => "xing", 
		"code" => "f168", 
	],
	[
		"name" => "Xing Square", 
		"icon" => "xing-square", 
		"code" => "f169", 
	],
	[
		"name" => "Y Combinator", 
		"icon" => "y-combinator", 
		"code" => "f23b", 
	],
	[
		"name" => "Yahoo", 
		"icon" => "yahoo", 
		"code" => "f19e", 
	],
	[
		"name" => "Yelp", 
		"icon" => "yelp", 
		"code" => "f1e9", 
	],
	[
		"name" => "Yoast", 
		"icon" => "yoast", 
		"code" => "f2b1", 
	],
	[
		"name" => "Youtube", 
		"icon" => "youtube", 
		"code" => "f167", 
	],
	[
		"name" => "Youtube Play", 
		"icon" => "youtube-play", 
		"code" => "f16a", 
	],
	[
		"name" => "Youtube Square", 
		"icon" => "youtube-square", 
		"code" => "f166", 
	],
];
